const fs = require('fs');
const path = require('path');

function formatStep(step) {
  let lines = [];
  lines.push('  {');
  lines.push(`    day: ${step.day},`);
  lines.push(`    month: ${step.month},`);
  lines.push(`    week: ${step.week},`);
  lines.push(`    title: ${JSON.stringify(step.title)},`);
  lines.push(`    building: ${JSON.stringify(step.building)},`);
  if (step.buildingTierLevel) {
    lines.push(`    buildingTierLevel: ${JSON.stringify(step.buildingTierLevel)},`);
  }
  if (step.buildingChoice) {
    lines.push('    buildingChoice: {');
    lines.push(`      type: ${JSON.stringify(step.buildingChoice.type)},`);
    lines.push(`      recommendedOption: ${JSON.stringify(step.buildingChoice.recommendedOption)},`);
    if (step.buildingChoice.alternativeOption) {
      lines.push(`      alternativeOption: ${JSON.stringify(step.buildingChoice.alternativeOption)},`);
    }
    lines.push(`      reason: ${JSON.stringify(step.buildingChoice.reason)},`);
    lines.push('    },');
  }
  
  const costParts = [];
  costParts.push(`gold: ${step.cost.gold}`);
  if (step.cost.wood) costParts.push(`wood: ${step.cost.wood}`);
  if (step.cost.ore) costParts.push(`ore: ${step.cost.ore}`);
  if (step.cost.gems) costParts.push(`gems: ${step.cost.gems}`);
  if (step.cost.crystal) costParts.push(`crystal: ${step.cost.crystal}`);
  if (step.cost.mercury) costParts.push(`mercury: ${step.cost.mercury}`);
  if (step.cost.alchemicalDust) costParts.push(`alchemicalDust: ${step.cost.alchemicalDust}`);
  lines.push(`    cost: { ${costParts.join(', ')} },`);

  lines.push('    heroActions: [');
  for (const act of step.heroActions) {
    lines.push(`      ${JSON.stringify(act)},`);
  }
  lines.push('    ],');

  lines.push(`    combatTactic: ${JSON.stringify(step.combatTactic)},`);
  lines.push(`    criticalTip: ${JSON.stringify(step.criticalTip)},`);
  lines.push(`    priority: ${JSON.stringify(step.priority)},`);
  lines.push('  },');
  return lines.join('\n');
}

// -----------------------------------------------------------------------------
// ENJAMBRE DAYS 15 - 56
// -----------------------------------------------------------------------------
const enjambreDays15To56 = [
  {
    day: 15,
    month: 1,
    week: 3,
    title: 'Día 15: Tier 6 - Madrigueras de Almas Ardientes (Burning Souls Burrows)',
    building: 'Madrigueras de Almas Ardientes (Burning Souls Burrows)',
    buildingTierLevel: 'Tier 6',
    cost: { gold: 5000, ore: 10, crystal: 6 },
    heroActions: [
      'Recluta los primeros Waurms de la colmena. Colosos excavadores con aliento de magma y terremoto sísmico.',
      'El héroe principal asalta el anillo medio neutral con apoyo de Reinas y Waurms.',
    ],
    combatTactic: 'El Waurm desata sismos y daño de fuego masivo para romper las filas rivales.',
    criticalTip: 'Aporta la capacidad de daño en área subterráneo y ruptura de formación enemiga.',
    priority: 'Alta',
  },
  {
    day: 16,
    month: 1,
    week: 3,
    title: 'Día 16: Mercado del Enjambre (Marketplace)',
    building: 'Mercado del Enjambre (Marketplace)',
    buildingTierLevel: 'Comercio e Intercambio',
    cost: { gold: 500, wood: 5 },
    heroActions: [
      'Construye el Mercado para intercambiar excedentes de madera por mineral y cristal.',
      'El explorador secundario bandera aserraderos y minas periféricas.',
    ],
    combatTactic: 'Optimiza la economía de la colonia para las mejoras de Semana 3 y 4.',
    criticalTip: 'Prerrequisito cívico obligatorio para el Depósito de Biomasa / Banco.',
    priority: 'Alta',
  },
  {
    day: 17,
    month: 1,
    week: 3,
    title: 'Día 17: Depósito de Biomasa / Banco (Bank - +500 Oro/día)',
    building: 'Depósito de Biomasa / Banco (Bank)',
    buildingTierLevel: 'Economía Avanzada',
    cost: { gold: 4000, wood: 10, ore: 10 },
    heroActions: [
      'Edifica el Banco para sumar renta pasiva de 500 de oro al día y consolidar intereses.',
      'El héroe principal limpia bancos de monstruos de alto nivel.',
    ],
    combatTactic: 'Financia las compras masivas de Reinas y Waurms en cada cambio de semana.',
    criticalTip: 'Garantiza liquidez permanente para la colmena antes de la Metrópolis.',
    priority: 'Alta',
  },
  {
    day: 18,
    month: 1,
    week: 3,
    title: 'Día 18: Silo de Recursos (+1 Cristal Diario para la Colmena)',
    building: 'Silo de Recursos (Resource Silo)',
    buildingTierLevel: 'Estructura de Recursos Raros • Prerrequisito: Mercado y Banco',
    cost: { gold: 0, gems: 3, crystal: 3 },
    heroActions: [
      'Erige el Silo de Recursos para iniciar la producción pasiva de +1 Cristal al día.',
      'El cristal es el recurso mágico fundamental de la Colmena para Waurms, Reinas y mejoras de quitina.',
    ],
    combatTactic: 'El suministro diario de cristal elimina cuellos de botella para las tropas superiores.',
    criticalTip: 'En Colmena el Silo de Recursos genera +1 Cristal diario. Coste de construcción 0 Oro.',
    priority: 'Alta',
  },
  {
    day: 19,
    month: 1,
    week: 3,
    title: 'Día 19: Silo Alquímico (Generador Diario de Polvo Alquímico)',
    building: 'Silo Alquímico (Alchemic Silo)',
    buildingTierLevel: 'Generador de Recursos Mágicos • Prerrequisito: Silo de Recursos',
    cost: { gold: 2000, ore: 5, crystal: 2, alchemicalDust: 25 },
    heroActions: [
      'Construye el Silo Alquímico para generar Polvo Alquímico imprescindible para mejorar moradas.',
      'El héroe principal avanza hacia el paso fronterizo del rival.',
    ],
    combatTactic: 'El polvo alquímico permite financiar los 100 de polvo requeridos para la Reina de la Colmena mejorada.',
    criticalTip: 'Imprescindible para costear las mejoras de Tiers 1 a 7 con ramas duales.',
    priority: 'Alta',
  },
  {
    day: 20,
    month: 1,
    week: 3,
    title: 'Día 20: Corazón del Apiario III (Metropolis - +4.000 Oro/día)',
    building: 'Corazón del Apiario III (Metropolis)',
    buildingTierLevel: 'Economía Máxima',
    cost: { gold: 10000, wood: 10, ore: 10 },
    heroActions: [
      'Alcanza el estatus de Metrópolis en la Colmena para consolidar 4.000 de oro al día.',
      'El ejército principal se reagrupa listo para la gran mejora de Tier 7 en Día 21.',
    ],
    combatTactic: 'Sustenta la compra del 100% del contingente semanal de todas las moradas.',
    criticalTip: 'Supremacía económica absoluta antes de la gran mejora de Tier 7.',
    priority: 'Crítica',
  },
  {
    day: 21,
    month: 1,
    week: 3,
    title: 'Día 21: Mejora de Tier 7 - Torre del Amor Mejorada (Madre de la Colmena vs Cazadora de Beelzebub)',
    building: 'Torre del Amor Mejorada',
    buildingTierLevel: 'Tier 7 Mejorado • Coste: 8.000 Oro, 10 Mineral, 8 Cristal, 100 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Madre de la Colmena (Eclosión de Parásitos en Combate & Aura de Fertilidad)',
      alternativeOption: 'Rama B: Cazadora de la Colmena (Vuelo Veloz, Aguijón Aniquilador & Frenesí Asesino)',
      reason: 'La Madre de la Colmena aporta refuerzos infinitos de Parásitos mientras desgasta al ejército rival.',
    },
    cost: { gold: 8000, ore: 10, crystal: 8, alchemicalDust: 100 },
    heroActions: [
      'Mejora la Torre del Amor para reclutar Madres de la Colmena / Cazadoras de la Colmena.',
      'Asalta fortalezas enemigas con la supremacía de Tier 7 de élite.',
    ],
    combatTactic: 'La Madre engendra enjambres continuos en casillas vacías absorbiendo ataques del rival.',
    criticalTip: 'Con Tier 7 mejorado en Día 21, la colmena domina el mapa con ventaja insalvable.',
    priority: 'Crítica',
  },
  {
    day: 22,
    month: 1,
    week: 4,
    title: 'Día 22: Mejora de Tier 6 - Madrigueras de Almas Ardientes Mejoradas (Waurms de Magma vs Cáusticos)',
    building: 'Madrigueras de Almas Ardientes Mejoradas',
    buildingTierLevel: 'Tier 6 Mejorado • Coste: 5.000 Oro, 10 Mineral, 4 Cristal, 50 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Waurm de Magma (Erupción Sísmica en Área & Aliento Igneo Devastador)',
      alternativeOption: 'Rama B: Waurm Cáustico (Túneles de Ácido Corrosivo & Disolución de Armadura)',
      reason: 'El Waurm de Magma pulveriza formaciones compactas con daño de fuego masivo.',
    },
    cost: { gold: 5000, ore: 10, crystal: 4, alchemicalDust: 50 },
    heroActions: [
      'Mejora las Madrigueras para incorporar Waurms de Magma.',
      'El ejército principal abre brecha en el territorio enemigo.',
    ],
    combatTactic: 'El Waurm ataca a través de casillas múltiples rompiendo la cobertura de tiradores rivales.',
    criticalTip: 'Potencia de fuego demoledora combinada con la presencia de la Reina.',
    priority: 'Alta',
  },
  {
    day: 23,
    month: 1,
    week: 4,
    title: 'Día 23: Cofradía de Magos Nivel 3 (Magia Primigenia y Nochesombra)',
    building: 'Cofradía de Magos Nivel 3',
    buildingTierLevel: 'Magia de Alto Nivel',
    cost: { gold: 3000, wood: 5, ore: 5, crystal: 6 },
    heroActions: [
      'Aprende hechizos de nivel 3: Niebla Ácida, Furia del Enjambre y Manto de Sombras.',
      'El héroe principal asalta el anillo exterior del oponente.',
    ],
    combatTactic: 'Lanza Furia del Enjambre para aumentar la iniciativa y daño de toda la colonia.',
    criticalTip: 'Sinergia brutal con la velocidad de Avispones y Saqueadores.',
    priority: 'Alta',
  },
  {
    day: 24,
    month: 1,
    week: 4,
    title: 'Día 24: Mejora de Tier 5 - Cúspide Mayor (Saqueadores Desgarradores vs Acorazados)',
    building: 'Cúspide Mayor (Apex Spire Mejorada)',
    buildingTierLevel: 'Tier 5 Mejorado • Coste: 4.000 Oro, 5 Madera, 4 Cristal, 35 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Saqueador Desgarrador (Depredador Ápice & Ataque sin Represalia)',
      alternativeOption: 'Rama B: Saqueador Acorazado (Quitina Reforzada & Resistencia a Magia)',
      reason: 'El Saqueador Desgarrador elimina unidades de élite enemigas sin recibir contragolpe.',
    },
    cost: { gold: 4000, wood: 5, crystal: 4, alchemicalDust: 35 },
    heroActions: [
      'Mejora a los Saqueadores a su forma Desgarradora.',
      'Captura la primera ciudad satélite o puesto de avanzada enemigo.',
    ],
    combatTactic: 'Despliega a los Saqueadores en flanco para ejecutar a campeones enemigos.',
    criticalTip: 'Pieza de choque indispensable para neutralizar tropas pesadas enemigas.',
    priority: 'Alta',
  },
  {
    day: 25,
    month: 1,
    week: 4,
    title: 'Día 25: Panal Real de Jalea (Tesorería / Treasury - +2.000 Oro/día)',
    building: 'Panal Real de Jalea (Treasury)',
    buildingTierLevel: 'Economía Máxima',
    cost: { gold: 5000, wood: 10, ore: 10 },
    heroActions: [
      'Construye la Tesorería para sumar +2.000 de oro al día adicionales.',
      'El segundo héroe consolida minas en el cuadrante conquistado.',
    ],
    combatTactic: 'Garantiza reservas de oro infinitas para sostener el reclutamiento total en el segundo mes.',
    criticalTip: 'La colmena alcanza ingresos de más de 7.000 oro diarios sumando Ayuntamiento, Banco y Tesorería.',
    priority: 'Alta',
  },
  {
    day: 26,
    month: 1,
    week: 4,
    title: 'Día 26: Mejora de Tier 3 - Gran Avispero (Avispones Cazadores vs Neurotóxicos)',
    building: 'Gran Avispero Mejorado',
    buildingTierLevel: 'Tier 3 Mejorado • Coste: 3.000 Oro, 5 Madera, 2 Cristal, 20 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Avispón Cazador (Vuelo de Largo Alcance & Picadura Venenosa Letal)',
      alternativeOption: 'Rama B: Avispón Neurotóxico (Parálisis de Objetivo & Supresión de Habilidades)',
      reason: 'El Avispón Cazador alcanza a los tiradores en el fondo de la cuadrícula en Turno 1.',
    },
    cost: { gold: 3000, wood: 5, crystal: 2, alchemicalDust: 20 },
    heroActions: [
      'Mejora a todos los Avispones para maximizar la velocidad de apertura en combate.',
      'Limpia puestos fronterizos y campamentos de artefactos.',
    ],
    combatTactic: 'Bloquea tiradores enemigos con los Avispones en Turno 1 evitando bajas en tus tropas.',
    criticalTip: 'Velocidad e iniciativa superiores para ganar siempre la iniciativa de turno.',
    priority: 'Alta',
  },
  {
    day: 27,
    month: 1,
    week: 4,
    title: 'Día 27: Comerciante de Artefactos de la Colmena (Artifact Merchant)',
    building: 'Comerciante de Artefactos (Artifact Merchant)',
    buildingTierLevel: 'Equipamiento de Héroe',
    cost: { gold: 2000, wood: 5, ore: 5 },
    heroActions: [
      'Equipa al comandante principal con artefactos que potencien Ataque, Velocidad y Poder Mágico.',
      'Vende reliquias no afines para acumular gemas y cristal.',
    ],
    combatTactic: 'Un héroe con artefactos de velocidad permite a toda la colmena actuar antes que el rival.',
    criticalTip: 'Optimiza las estadísticas del comandante antes del inicio del Mes 2.',
    priority: 'Media',
  },
  {
    day: 28,
    month: 1,
    week: 4,
    title: 'Día 28: Cámara de Feromonas / Glándula de Asimilación (Estructura Única)',
    building: 'Cámara de Feromonas (Estructura Única)',
    buildingTierLevel: 'Estructura Exclusiva de Facción',
    cost: { gold: 5000, ore: 10, crystal: 5 },
    heroActions: [
      'Construye la Cámara de Feromonas para aumentar la moral y resistencia de todas las criaturas de la Colmena.',
      'Prepara el ejército para la gran ofensiva de la Semana 5.',
    ],
    combatTactic: 'Las feromonas anulan cualquier penalizador de moral y otorgan inmunidad a efectos de miedo.',
    criticalTip: 'Cierre magistral del Mes 1: ejército completo, Tier 7 mejorado y economía colosal.',
    priority: 'Crítica',
  },
  {
    day: 29,
    month: 2,
    week: 5,
    title: 'Día 29: Mejora de Tier 2 - Fosa de Carroña (Langostas Carroñeras vs Devoradoras)',
    building: 'Fosa de Carroña Mejorada',
    buildingTierLevel: 'Tier 2 Mejorado • Coste: 2.500 Oro, 5 Mineral, 15 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Langosta Carroñera (Voracidad Insaciable & Consunción de Caídos)',
      alternativeOption: 'Rama B: Langosta Devoradora (Salto de Emboscada & Daño Corrosivo)',
      reason: 'La Langosta Carroñera regenera salud consumiendo restos de tropas enemigas caídas.',
    },
    cost: { gold: 2500, ore: 5, alchemicalDust: 15 },
    heroActions: [
      'Mejora todo el contingente acumulado de Langostas.',
      'Reúne las hordas del nuevo mes en el héroe principal.',
    ],
    combatTactic: 'Lanza a las Langostas en oleadas de desgaste para ablandar al ejército defensor.',
    criticalTip: 'Multiplicador de masa brutal con costes reducidos.',
    priority: 'Alta',
  },
  {
    day: 30,
    month: 2,
    week: 5,
    title: 'Día 30: Mejora de Tier 1 - Cámara de Infestación (Parásitos Voraces vs Espinosos)',
    building: 'Cámara de Infestación (Vivienda Mejorada)',
    buildingTierLevel: 'Tier 1 Mejorado • Coste: 2.000 Oro, 5 Madera, 10 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Parásito Voraz (Alcance Largo & Derribo de Colosos)',
      alternativeOption: 'Rama B: Parásito Espinoso (Piel de Púas Quitinosas & Daño Reflejado)',
      reason: 'El Parásito Voraz ataca a 2 casillas sin sufrir contragolpe y castiga a criaturas de alto tier.',
    },
    cost: { gold: 2000, wood: 5, alchemicalDust: 10 },
    heroActions: [
      'Actualiza las miles de unidades de Parásitos para su uso en asedios masivos.',
      'El ejército principal cruza la cordillera hacia la capital rival.',
    ],
    combatTactic: 'Posiciona a los Parásitos Voraces tras los Waurms para rematar colosos rivales sin riesgo.',
    criticalTip: 'Con todas las moradas mejoradas, el ejército del Enjambre es imparable.',
    priority: 'Alta',
  },
  {
    day: 31,
    month: 2,
    week: 5,
    title: 'Día 31: Cofradía de Magos Nivel 4 (Hechizos de Plaga y Devastación)',
    building: 'Cofradía de Magos Nivel 4',
    buildingTierLevel: 'Magia Maestra',
    cost: { gold: 4000, wood: 5, ore: 5, crystal: 8 },
    heroActions: [
      'Aprende hechizos de nivel 4: Enjambre Devorador, Terremoto y Lluvia Ácida de Gran Escala.',
      'El comandante principal alcanza nivel 14-16.',
    ],
    combatTactic: 'Lanza Enjambre Devorador para asfixiar las defensas de castillos y murallas enemigas.',
    criticalTip: 'Los hechizos de nivel 4 destruyen fortificaciones y diezman ejércitos acampados.',
    priority: 'Alta',
  },
  {
    day: 32,
    month: 2,
    week: 5,
    title: 'Día 32: Glándula de Eclosión Acelerada (+25% Crecimiento Insectoide)',
    building: 'Glándula de Eclosión Acelerada',
    buildingTierLevel: 'Crecimiento de Criaturas',
    cost: { gold: 4000, wood: 5, ore: 5 },
    heroActions: [
      'Construye la Glándula para incrementar el crecimiento semanal de todas las moradas en +25%.',
      'El héroe secundario asegura la cadena de refuerzos hacia el frente.',
    ],
    combatTactic: 'Aumenta el flujo de reclutamiento para reponer cualquier pérdida instantáneamente.',
    criticalTip: 'Suma acumulación de criaturas masiva que supera con creces la tasa de cualquier rival.',
    priority: 'Alta',
  },
  {
    day: 33,
    month: 2,
    week: 5,
    title: 'Día 33: Depósito Alquímico Avanzado (+1 Polvo Alquímico Diario Adicional)',
    building: 'Depósito Alquímico Avanzado',
    buildingTierLevel: 'Economía Alquímica • Coste: 3.000 Oro, 4 Cristal, 25 Polvo Alquímico',
    cost: { gold: 3000, crystal: 4, alchemicalDust: 25 },
    heroActions: [
      'Amplía las instalaciones alquímicas para duplicar la producción diaria de Polvo.',
      'Permite financiar mejoras en ciudades capturadas y tecnologías astrales.',
    ],
    combatTactic: 'El polvo constante financia el Observatorio y las leyes de máximo rango.',
    criticalTip: 'Soporte fundamental para la dominación tecnológica del segundo mes.',
    priority: 'Media',
  },
  {
    day: 34,
    month: 2,
    week: 5,
    title: 'Día 34: Bastión Quitináceo de Frontera (Torreón Defensivo)',
    building: 'Bastión Quitináceo Exterior',
    buildingTierLevel: 'Defensa Territorial',
    cost: { gold: 3000, ore: 10 },
    heroActions: [
      'Fortifica el paso clave que conecta tu territorio con el del adversario.',
      'El ejército principal inicia el cerco sobre el primer bastión enemigo.',
    ],
    combatTactic: 'El bastión repele incursiones secundarias de exploración del rival sin distraer al ejército central.',
    criticalTip: 'Asegura tu retaguardia mientras tu fuerza principal opera en territorio enemigo.',
    priority: 'Media',
  },
  {
    day: 35,
    month: 2,
    week: 5,
    title: 'Día 35: Refinería de Cristal de la Colmena (Conversión Eficiente de Recursos)',
    building: 'Refinería de Cristal',
    buildingTierLevel: 'Conversión de Recursos Raros',
    cost: { gold: 4000, ore: 5, crystal: 4 },
    heroActions: [
      'Edifica la Refinería para convertir excedentes de mineral en Cristal a una tasa óptima.',
      'Recluta un contingente fresco de Reinas y Waurms.',
    ],
    combatTactic: 'Garantiza que nunca falte Cristal para hechizos y reclutamiento de alto nivel.',
    criticalTip: 'Autosuficiencia en el recurso más crítico de la facción.',
    priority: 'Alta',
  },
  {
    day: 36,
    month: 2,
    week: 6,
    title: 'Día 36: Asentamiento Secundario (Town Hall en Ciudad Capturada)',
    building: 'Asentamiento Secundario (Town Hall)',
    buildingTierLevel: 'Expansión Territorial',
    cost: { gold: 2500 },
    heroActions: [
      'Reconstruye la sede cívica de la ciudad recién conquistada para convertirla en nodo del enjambre.',
      'Establece guarnición con tropas de tiers intermedios.',
    ],
    combatTactic: 'La ciudad capturada se convierte en un centro logístico avanzado en territorio rival.',
    criticalTip: 'Genera +1.000 de oro al día y permite reclutar héroes en el frente de batalla.',
    priority: 'Alta',
  },
  {
    day: 37,
    month: 2,
    week: 6,
    title: 'Día 37: Red de Túneles Subterráneos de la Colmena (Teletransporte Regional)',
    building: 'Red de Túneles Subterráneos',
    buildingTierLevel: 'Movilidad Estratégica',
    cost: { gold: 5000, ore: 10, crystal: 5 },
    heroActions: [
      'Cava la red de túneles que conecta la capital con la ciudad secundaria.',
      'El héroe principal se desplaza al instante entre bases reforzando ambos frentes.',
    ],
    combatTactic: 'Permite transferir tropas sin consumir puntos de movimiento en el mapa de aventura.',
    criticalTip: 'Movilidad estratégica insuperable que descoloca la defensa enemiga.',
    priority: 'Crítica',
  },
  {
    day: 38,
    month: 2,
    week: 6,
    title: 'Día 38: Fortificaciones de la Segunda Colmena (Fortifications I)',
    building: 'Fortificaciones de la Segunda Colmena',
    buildingTierLevel: 'Defensa de Base Avanzada',
    cost: { gold: 2500, ore: 5 },
    heroActions: [
      'Erige murallas defensivas en el asentamiento secundario.',
      'El explorador patrulla las rutas de escape del rival.',
    ],
    combatTactic: 'Impide contraofensivas relámpago contra tu base de suministro.',
    criticalTip: 'Base fortificada segura para acopiar tropas recién engendradas.',
    priority: 'Media',
  },
  {
    day: 39,
    month: 2,
    week: 6,
    title: 'Día 39: Segundo Nido de Papel (Avispones Secundarios)',
    building: 'Segundo Nido de Papel',
    buildingTierLevel: 'Producción Militar Adicional',
    cost: { gold: 1500, wood: 5, crystal: 2 },
    heroActions: [
      'Construye una morada de Avispones en la base secundaria para sumar crecimiento adicional.',
      'El comandante asalta las reservas de artefactos del rival.',
    ],
    combatTactic: 'Multiplica la presencia de tiradores y voladores rápidos en ambos frentes.',
    criticalTip: 'Crecimiento paralelo de criaturas rápidas para control de mapa.',
    priority: 'Alta',
  },
  {
    day: 40,
    month: 2,
    week: 6,
    title: 'Día 40: Segunda Cúspide de Saqueadores (Apex Secundario)',
    building: 'Segunda Cúspide (Apex Secundario)',
    buildingTierLevel: 'Producción Militar Tier 5 Adicional',
    cost: { gold: 3500, wood: 5, crystal: 4 },
    heroActions: [
      'Añade una segunda morada de Saqueadores.',
      'El ejército principal cerca el segundo castillo rival.',
    ],
    combatTactic: 'Genera escuadras de choque en la retaguardia enemiga.',
    criticalTip: 'Doble producción de unidades con ataque sin represalia.',
    priority: 'Alta',
  },
  {
    day: 41,
    month: 2,
    week: 6,
    title: 'Día 41: Ciudadela de la Segunda Colmena (+50% Crecimiento Secundario)',
    building: 'Ciudadela de la Segunda Colmena (Citadel)',
    buildingTierLevel: 'Crecimiento Militar Secundario',
    cost: { gold: 2500, ore: 10 },
    heroActions: [
      'Aumenta el crecimiento de la base secundaria en +50%.',
      'Prepara los recursos para duplicar la producción de Tier 7.',
    ],
    combatTactic: 'Refuerzos masivos listos para la batalla decisiva de la Semana 7.',
    criticalTip: 'Capacidad de reclutamiento desbordante.',
    priority: 'Alta',
  },
  {
    day: 42,
    month: 2,
    week: 6,
    title: 'Día 42: Segunda Torre del Amor (Torre de Reinas Secundaria)',
    building: 'Segunda Torre del Amor (Tower of Love)',
    buildingTierLevel: 'Producción Militar Tier 7 Adicional',
    cost: { gold: 10000, ore: 15, crystal: 10 },
    heroActions: [
      'Construye la segunda Torre del Amor para duplicar el reclutamiento de Reinas de la Colmena.',
      'Recluta un contingente adicional de Reinas para formar un segundo ejército de invasión.',
    ],
    combatTactic: 'Dos ejércitos con Reinas de la Colmena operando en pinza sobre el adversario.',
    criticalTip: 'Tener dos moradas de Tier 7 activas garantiza superioridad militar irreversible.',
    priority: 'Crítica',
  },
  {
    day: 43,
    month: 2,
    week: 7,
    title: 'Día 43: Cofradía de Magos Nivel 5 (Plagas Arcanas & Eclosión Suprema)',
    building: 'Cofradía de Magos Nivel 5',
    buildingTierLevel: 'Magia Divina / Primigenia Suprema',
    cost: { gold: 5000, wood: 5, ore: 5, crystal: 10 },
    heroActions: [
      'Aprende hechizos supremos de nivel 5: Eclosión Masiva, Teletransporte de Túneles y Holocausto de Ácido.',
      'El héroe principal domina todo el grimorio mágico.',
    ],
    combatTactic: 'Teletransporta al ejército completo directamente dentro de las murallas del último bastión enemigo.',
    criticalTip: 'El control mágico supremo elimina la ventaja defensiva de cualquier fortaleza rival.',
    priority: 'Crítica',
  },
  {
    day: 44,
    month: 2,
    week: 7,
    title: 'Día 44: Trono de la Supermente (+2 Moral y +2 Suerte a Insectoides)',
    building: 'Trono de la Supermente (Monumento Supremo)',
    buildingTierLevel: 'Monumento de Facción',
    cost: { gold: 6000, crystal: 6 },
    heroActions: [
      'Erige el Trono de la Supermente para otorgar +2 de Moral y +2 de Suerte permanentes a todas las tropas.',
      'El ejército principal inicia la ofensiva final.',
    ],
    combatTactic: 'Tasa altísima de golpes afortunados críticos y turnos adicionales por moral radiante.',
    criticalTip: 'Multiplica la efectividad de cada pila de criaturas en combate.',
    priority: 'Alta',
  },
  {
    day: 45,
    month: 2,
    week: 7,
    title: 'Día 45: Segundo Silo de Recursos Regional (+1 Cristal Diario Adicional)',
    building: 'Segundo Silo de Recursos',
    buildingTierLevel: 'Economía Regional',
    cost: { gold: 0, gems: 3, crystal: 3 },
    heroActions: [
      'Añade un segundo silo para acumular +2 Cristales diarios en el reino.',
      'El héroe secundario asegura las rutas de marcha militar.',
    ],
    combatTactic: 'Sustenta el gasto continuo de maná y reposición de colosos.',
    criticalTip: 'Recursos infinitos para las dos semanas de clímax.',
    priority: 'Media',
  },
  {
    day: 46,
    month: 2,
    week: 7,
    title: 'Día 46: Mejora de Segunda Torre de Reinas (Madres de la Colmena Adicionales)',
    building: 'Segunda Torre del Amor Mejorada',
    buildingTierLevel: 'Tier 7 Mejorado Secundario • Coste: 8.000 Oro, 10 Mineral, 8 Cristal, 100 Polvo Alquímico',
    cost: { gold: 8000, ore: 10, crystal: 8, alchemicalDust: 100 },
    heroActions: [
      'Mejora la segunda Torre del Amor para reclutar Madres de la Colmena en ambos frentes.',
      'Equipa a los dos comandantes con el contingente de élite.',
    ],
    combatTactic: 'Despliega Madres de la Colmena en ambas alas de batalla para generar parásitos en todo el campo.',
    criticalTip: 'Dominio absoluto de la masa de criaturas en el campo de batalla.',
    priority: 'Crítica',
  },
  {
    day: 47,
    month: 2,
    week: 7,
    title: 'Día 47: Red de Feromonas Global (Visión Compartida en Jadame)',
    building: 'Red de Feromonas Global',
    buildingTierLevel: 'Información y Exploración Total',
    cost: { gold: 5000, wood: 10, crystal: 5 },
    heroActions: [
      'Dispersa las feromonas para disipar la niebla de guerra en todo el mapa de Jadame.',
      'Localiza la posición exacta de cada héroe y ejército enemigo.',
    ],
    combatTactic: 'Intercepta y embosca a los héroes rivales en terreno favorable sin margen de escape.',
    criticalTip: 'Visión completa del mapa de aventura para asestar el golpe de gracia.',
    priority: 'Alta',
  },
  {
    day: 48,
    month: 2,
    week: 7,
    title: 'Día 48: Vórtice de Asimilación de Almas (+10% Daño de Hechizos del Enjambre)',
    building: 'Vórtice de Asimilación de Almas',
    buildingTierLevel: 'Potenciador Arcano de Facción',
    cost: { gold: 4000, crystal: 6 },
    heroActions: [
      'Construye el Vórtice para amplificar el poder de conjuro de todos los hechiceros de la colmena en un +10%.',
      'El comandante principal prepara su reserva de maná para el asedio supremo.',
    ],
    combatTactic: 'Maximiza el daño de proyectiles mágicos y plagas sobre las tropas más blindadas del rival.',
    criticalTip: 'Asegura que los hechizos eliminen pilas completas con un solo lanzamiento.',
    priority: 'Alta',
  },
  {
    day: 49,
    month: 2,
    week: 7,
    title: 'Día 49: Gran Almacén Quitináceo (Reducción de Costes de Mantenimiento)',
    building: 'Gran Almacén Quitináceo',
    buildingTierLevel: 'Optimización Logística',
    cost: { gold: 3500, ore: 10 },
    heroActions: [
      'Almacena reservas para abastecer el reclutamiento total del último lunes de la campaña.',
      'Los exploradores se posicionan para guiar la marcha de la horda.',
    ],
    combatTactic: 'Concentra la totalidad del inventario de oro en la compra de la armada definitiva.',
    criticalTip: 'Prepara el último gran día de compras del Día 50.',
    priority: 'Media',
  },
  {
    day: 50,
    month: 2,
    week: 8,
    title: 'Día 50: Herrería Quitinácea (Arietes y Catapultas de Ácido de la Colmena)',
    building: 'Herrería Quitinácea (Maquinaria de Asedio)',
    buildingTierLevel: 'Maquinaria de Guerra',
    cost: { gold: 3000, wood: 5, ore: 5 },
    heroActions: [
      'Fabrica la catapulta de ácido y balistas quitinosas para el asedio final.',
      'El ejército principal se agrupa ante las puertas de la capital del último oponente.',
    ],
    combatTactic: 'La catapulta de ácido disuelve murallas y fosos en Turno 1 permitiendo la entrada directa de Waurms.',
    criticalTip: 'Derriba las defensas del castillo enemigo sin sufrir daño de torres defensivas.',
    priority: 'Alta',
  },
  {
    day: 51,
    month: 2,
    week: 8,
    title: 'Día 51: Fosa de Eclosión Suprema (+50% Capacidad de Reserva de Tropas)',
    building: 'Fosa de Eclosión Suprema',
    buildingTierLevel: 'Capacidad Máxima Militar',
    cost: { gold: 5000, ore: 10, crystal: 5 },
    heroActions: [
      'Expande la reserva de tropas para acumular un excedente masivo de Parásitos y Avispones.',
      'Se completa el ensamblaje de la horda de invasión.',
    ],
    combatTactic: 'Supera en número al rival en una proporción de 5 a 1 en el campo de batalla.',
    criticalTip: 'Masa crítica definitiva que anula cualquier estrategia de microtáctica enemiga.',
    priority: 'Alta',
  },
  {
    day: 52,
    month: 2,
    week: 8,
    title: 'Día 52: Reclutamiento Masivo de la Horda de Waurms y Reinas de la Colmena',
    building: 'Reclutamiento Supremo de la Horda',
    buildingTierLevel: 'Reclutamiento Militar Final',
    cost: { gold: 12000, crystal: 10 },
    heroActions: [
      'Compra la totalidad de las Reinas de la Colmena, Waurms de Magma y Saqueadores disponibles en ambas ciudades.',
      'El ejército alcanza su poder máximo histórico en Jadame.',
    ],
    combatTactic: 'Formación hexagonal completa con vanguardia de Waurms, flancos de Saqueadores y núcleo de Madres.',
    criticalTip: 'La mayor fuerza militar jamás reunida por la facción de la Colmena.',
    priority: 'Crítica',
  },
  {
    day: 53,
    month: 2,
    week: 8,
    title: 'Día 53: Sellado de Pasos Estratégicos con Nidos Defensivos Avanzados',
    building: 'Nidos Defensivos de Paso',
    buildingTierLevel: 'Control Defensivo del Territorio',
    cost: { gold: 4000, ore: 8 },
    heroActions: [
      'Sella todos los portales y pasos de montaña para evitar que el rival intente maniobras de escape.',
      'El adversario queda atrapado en su última fortaleza.',
    ],
    combatTactic: 'Aísla al general enemigo sin posibilidad de recibir refuerzos.',
    criticalTip: 'Cierre total de las vías de suministros del adversario.',
    priority: 'Media',
  },
  {
    day: 54,
    month: 2,
    week: 8,
    title: 'Día 54: Bendición de la Supermente (+3 Iniciativa a Todas las Criaturas de la Colmena)',
    building: 'Altar de la Supermente (Bendición Suprema)',
    buildingTierLevel: 'Bendición de Batalla',
    cost: { gold: 6000, crystal: 8 },
    heroActions: [
      'Canaliza la bendición de la Supermente para otorgar +3 de Iniciativa y +20% de Velocidad a todo el ejército.',
      'Las tropas actúan en primer lugar en todas las fases del combate.',
    ],
    combatTactic: 'Ataca con todo el ejército antes de que el adversario pueda lanzar su primer hechizo o ataque.',
    criticalTip: 'Garantiza la aniquilación de la primera línea enemiga antes de que puedan reaccionar.',
    priority: 'Crítica',
  },
  {
    day: 55,
    month: 2,
    week: 8,
    title: 'Día 55: Marcha de Guerra de la Horda Insectoide hacia la Última Fortaleza Enemiga',
    building: 'Marcha de Guerra del Enjambre',
    buildingTierLevel: 'Fase Ofensiva Final',
    cost: { gold: 5000 },
    heroActions: [
      'Inicia el asedio directo a la capital enemiga con las catapultas de ácido y el ejército completo.',
      'Destruye las torres de guardia exteriores.',
    ],
    combatTactic: 'Disuelve las murallas con ácido mientras los Avispones eliminan a los tiradores en las torres.',
    criticalTip: 'Último asalto para la conquista completa de Jadame.',
    priority: 'Crítica',
  },
  {
    day: 56,
    month: 2,
    week: 8,
    title: 'Día 56: Consunción Total de Jadame: Victoria Absoluta de la Colmena de Beelzebub',
    building: 'Nido Supremo de la Supermente',
    buildingTierLevel: 'Consumación de la Campaña',
    cost: { gold: 15000, ore: 20, crystal: 15 },
    heroActions: [
      'Asimilación final de todas las fortalezas y facciones rivales del continente de Jadame.',
      'Victoria total y definitiva de la Colmena tras 56 días de ejecución estratégica perfecta.',
    ],
    combatTactic: 'Hordas interminables de Reinas de la Colmena, Waurms de Magma y Saqueadores Ápice aplastan cualquier resistencia.',
    criticalTip: '¡Estrategia de 56 días de Enjambre completada con éxito impecable y rigor canónico absoluto!',
    priority: 'Crítica',
  },
];

console.log('Enjambre steps 15-56 prepared:', enjambreDays15To56.length);

module.exports = { enjambreDays15To56, formatStep };
