const fs = require('fs');
const path = require('path');

function formatStep(step) {
  let lines = [];
  lines.push('  {');
  lines.push(`    day: ${step.day},`);
  lines.push(`    month: ${step.month},`);
  lines.push(`    week: ${step.week},`);
  lines.push(`    title: ${JSON.stringify(step.title)},`);
  lines.push(`    building: ${JSON.stringify(step.building)},`);
  if (step.buildingTierLevel) {
    lines.push(`    buildingTierLevel: ${JSON.stringify(step.buildingTierLevel)},`);
  }
  if (step.buildingChoice) {
    lines.push('    buildingChoice: {');
    lines.push(`      type: ${JSON.stringify(step.buildingChoice.type)},`);
    lines.push(`      recommendedOption: ${JSON.stringify(step.buildingChoice.recommendedOption)},`);
    if (step.buildingChoice.alternativeOption) {
      lines.push(`      alternativeOption: ${JSON.stringify(step.buildingChoice.alternativeOption)},`);
    }
    lines.push(`      reason: ${JSON.stringify(step.buildingChoice.reason)},`);
    lines.push('    },');
  }
  
  const costParts = [];
  costParts.push(`gold: ${step.cost.gold}`);
  if (step.cost.wood) costParts.push(`wood: ${step.cost.wood}`);
  if (step.cost.ore) costParts.push(`ore: ${step.cost.ore}`);
  if (step.cost.gems) costParts.push(`gems: ${step.cost.gems}`);
  if (step.cost.crystal) costParts.push(`crystal: ${step.cost.crystal}`);
  if (step.cost.mercury) costParts.push(`mercury: ${step.cost.mercury}`);
  if (step.cost.alchemicalDust) costParts.push(`alchemicalDust: ${step.cost.alchemicalDust}`);
  lines.push(`    cost: { ${costParts.join(', ')} },`);

  lines.push('    heroActions: [');
  for (const act of step.heroActions) {
    lines.push(`      ${JSON.stringify(act)},`);
  }
  lines.push('    ],');

  lines.push(`    combatTactic: ${JSON.stringify(step.combatTactic)},`);
  lines.push(`    criticalTip: ${JSON.stringify(step.criticalTip)},`);
  lines.push(`    priority: ${JSON.stringify(step.priority)},`);
  lines.push('  },');
  return lines.join('\n');
}

// ARBOLEDA DAYS 15-56
const arboledaDays15To56 = [
  {
    day: 15,
    month: 1,
    week: 3,
    title: 'Día 15: Mejora de Tier 6 - Guarida del Trueno Mejorada (Qilin Celeste vs Tormentoso)',
    building: 'Guarida del Trueno Mejorada',
    buildingTierLevel: 'Tier 6 Mejorado • Coste: 4.500 Oro, 5 Madera, 4 Gemas, 50 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Qilin Celeste (Sendero de Niebla Protectora & Carga Celestial Veloz)',
      alternativeOption: 'Rama B: Qilin Tormentoso (Descarga de Trueno en Área & Choque Paralizante)',
      reason: 'El Qilin Celeste otorga niebla que protege a tus tiradores y cruza el mapa táctico en Turno 1.',
    },
    cost: { gold: 4500, wood: 5, gems: 4, alchemicalDust: 50 },
    heroActions: [
      'Mejora la Guarida del Trueno para incorporar Qilins celestes al ejército principal.',
      'El Fénix y los Qilins combinados ofrecen iniciativa y velocidad absolutas en el mapa.',
    ],
    combatTactic: 'Cruza el tablero con los Qilins celestes para bloquear a los atacantes enemigos y desplegar el sendero de niebla.',
    criticalTip: 'Supremacía en movilidad y control de terreno en los compases iniciales de la Semana 3.',
    priority: 'Crítica',
  },
  {
    day: 16,
    month: 1,
    week: 3,
    title: 'Día 16: Mercado Silvano (Marketplace)',
    building: 'Mercado Silvano (Marketplace)',
    buildingTierLevel: 'Comercio e Intercambio',
    cost: { gold: 500, wood: 5 },
    heroActions: [
      'Construye el Mercado para intercambiar excedentes de madera por Gemas y Cristales.',
      'El héroe secundario asegura carretas de suministros y minas capturadas.',
    ],
    combatTactic: 'Estabiliza la balanza de recursos mágicos para no frenar la inversión en moradas de élite.',
    criticalTip: 'Prerrequisito cívico obligatorio para el Banco Silvano y el Silo de Recursos.',
    priority: 'Alta',
  },
  {
    day: 17,
    month: 1,
    week: 3,
    title: 'Día 17: Banco Silvano / Almacén del Roble (Bank - +500 Oro/día)',
    building: 'Banco Silvano (Bank)',
    buildingTierLevel: 'Economía Avanzada',
    cost: { gold: 4000, wood: 10, ore: 10 },
    heroActions: [
      'Edifica el Banco para sumar renta pasiva de 500 de oro al día y acumular reservas.',
      'El héroe principal limpia santuarios protegidos por elementales.',
    ],
    combatTactic: 'Financia las costosas compras semanales de Fénix y Qilins cada lunes.',
    criticalTip: 'Garantiza liquidez permanente para la facción silvana antes de la Metrópolis.',
    priority: 'Alta',
  },
  {
    day: 18,
    month: 1,
    week: 3,
    title: 'Día 18: Silo de Recursos (+1 Gema y +1 Cristal Diarios para Arboleda)',
    building: 'Silo de Recursos (Resource Silo)',
    buildingTierLevel: 'Estructura de Recursos Raros • Prerrequisito: Mercado y Banco',
    cost: { gold: 0, gems: 3, crystal: 3 },
    heroActions: [
      'Erige el Silo de Recursos para iniciar la producción pasiva de +1 Gema y +1 Cristal al día.',
      'Abastece el continuo gasto de recursos raros de los Fénix, Herbomantes y Cofradía de Magos.',
    ],
    combatTactic: 'El flujo pasivo de gemas y cristales sostiene la hechicería y las mejoras magistrales.',
    criticalTip: 'En Arboleda el Silo de Recursos genera los recursos mágicos primarios de la facción. Coste de construcción 0 Oro.',
    priority: 'Alta',
  },
  {
    day: 19,
    month: 1,
    week: 3,
    title: 'Día 19: Silo Alquímico (Generador Diario de Polvo Alquímico)',
    building: 'Silo Alquímico (Alchemic Silo)',
    buildingTierLevel: 'Generador de Recursos Mágicos • Prerrequisito: Silo de Recursos',
    cost: { gold: 2000, wood: 5, crystal: 2, alchemicalDust: 25 },
    heroActions: [
      'Construye el Silo Alquímico para generar Polvo Alquímico de forma continuada.',
      'El héroe principal asalta el anillo exterior del oponente más próximo.',
    ],
    combatTactic: 'El polvo alquímico permite financiar los 100 de polvo requeridos para la mejora del Fénix.',
    criticalTip: 'Imprescindible para desbloquear las ramas duales de mejora en todas las criaturas.',
    priority: 'Alta',
  },
  {
    day: 20,
    month: 1,
    week: 3,
    title: 'Día 20: Palacio de la Arboleda III (Metropolis - +4.000 Oro/día)',
    building: 'Palacio de la Arboleda III (Metropolis)',
    buildingTierLevel: 'Economía Máxima',
    cost: { gold: 10000, wood: 10, ore: 10 },
    heroActions: [
      'Alcanza el estatus de Metrópolis en Arboleda para consolidar 4.000 de oro al día.',
      'El ejército principal se reagrupa cerca de la capital listo para la gran mejora de Tier 7.',
    ],
    combatTactic: 'Sustenta la compra del 100% de la producción de todas las moradas silvanas.',
    criticalTip: 'Supremacía económica absoluta antes de la gran mejora de Tier 7.',
    priority: 'Crítica',
  },
  {
    day: 21,
    month: 1,
    week: 3,
    title: 'Día 21: Mejora de Tier 7 - Pira Sagrada Mejorada (Fénix de Luz vs Fénix Solar)',
    building: 'Pira Sagrada Mejorada',
    buildingTierLevel: 'Tier 7 Mejorado • Coste: 8.000 Oro, 10 Madera, 8 Cristal, 8 Gemas, 100 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Fénix de Luz (Renacimiento Completo con 100% Vida & Aura de Resplandor)',
      alternativeOption: 'Rama B: Fénix de Brasa Solar (Explosión Ígnea al Morir & Aliento de Fuego en Cono)',
      reason: 'El Fénix de Luz garantiza que tu coloso regrese al combate con toda su salud restaurada sin pérdidas.',
    },
    cost: { gold: 8000, wood: 10, crystal: 8, gems: 8, alchemicalDust: 100 },
    heroActions: [
      'Mejora la Pira para reclutar los legendarios Fénix de Luz de Arboleda.',
      'Asalta las fortalezas enemigas con la criatura de mayor iniciativa y renacimiento de Jadame.',
    ],
    combatTactic: 'El Fénix vuela por encima de murallas y obstáculos, desatando daño de fuego y resucitando de sus cenizas.',
    criticalTip: 'Con Tier 7 mejorado en Día 21, el ejército silvano es indestructible.',
    priority: 'Crítica',
  },
  {
    day: 22,
    month: 1,
    week: 4,
    title: 'Día 22: Mejora de Tier 5 - Choza de Maderahongo Mejorada (Herbomantes Espóricos vs Sanadores)',
    building: 'Choza de Maderahongo Mejorada',
    buildingTierLevel: 'Tier 5 Mejorado • Coste: 3.500 Oro, 5 Madera, 3 Gemas, 35 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Herbomante Espórico (Nube de Esporas Fúngicas Debilitantes & Daño Mágico)',
      alternativeOption: 'Rama B: Herbomante Sanador (Regeneración Botánica Continua & Purificación de Aliados)',
      reason: 'El Herbomante Espórico reduce las defensas y el ataque de los colosos rivales en cada ronda.',
    },
    cost: { gold: 3500, wood: 5, gems: 3, alchemicalDust: 35 },
    heroActions: [
      'Mejora a los Herbomantes para maximizar el soporte mágico y debilitación en combate.',
      'El ejército principal abre brecha en el territorio enemigo.',
    ],
    combatTactic: 'Combina las esporas de los Herbomantes con el fuego del Fénix para eliminar escuadras pesadas.',
    criticalTip: 'Soporte vital para prolongar la resistencia de la primera línea de combate.',
    priority: 'Alta',
  },
  {
    day: 23,
    month: 1,
    week: 4,
    title: 'Día 23: Cofradía de Magos Silvana Nivel 3 (Magia de Luz y Primigenia)',
    building: 'Cofradía de Magos Nivel 3',
    buildingTierLevel: 'Magia de Alto Nivel',
    cost: { gold: 3000, wood: 5, ore: 5, gems: 4, crystal: 4 },
    heroActions: [
      'Aprende hechizos de nivel 3: Vástago de la Tierra, Aura Solar y Escudo de Espinas.',
      'El héroe principal asalta el territorio enemigo exterior.',
    ],
    combatTactic: 'Lanza Aura Solar sobre las criaturas de choque para castigar cualquier contragolpe enemigo.',
    criticalTip: 'Sinergia perfecta con los Hoplitas y Qilins en combate cerrado.',
    priority: 'Alta',
  },
  {
    day: 24,
    month: 1,
    week: 4,
    title: 'Día 24: Mejora de Tier 4 - Estanque Floreciente Mejorado (Aqualotls de Marisma vs Glaciares)',
    building: 'Estanque Floreciente Mejorado',
    buildingTierLevel: 'Tier 4 Mejorado • Coste: 3.000 Oro, 5 Madera, 3 Cristal, 25 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Aqualotl Glaciar (Aliento Gélido Ralentizador & Congelación de Hexágonos)',
      alternativeOption: 'Rama B: Aqualotl de Marisma (Veneno Anfibio Corrosivo & Camuflaje de Ciénaga)',
      reason: 'El Aqualotl Glaciar congela casillas impidiendo que los atacantes pesados rivales alcancen tu línea.',
    },
    cost: { gold: 3000, wood: 5, crystal: 3, alchemicalDust: 25 },
    heroActions: [
      'Mejora a los Aqualotls a su forma Glaciar para un control de campo letal.',
      'Captura la primera ciudad satélite o puesto de avanzada enemigo.',
    ],
    combatTactic: 'Lanza a los Aqualotls para congelar a los colosos enemigos y reducir su iniciativa.',
    criticalTip: 'Control de multitudes esencial contra ejércitos con alta movilidad.',
    priority: 'Alta',
  },
  {
    day: 25,
    month: 1,
    week: 4,
    title: 'Día 25: Tesorería Silvana (Treasury - +2.000 Oro/día)',
    building: 'Tesorería Silvana (Treasury)',
    buildingTierLevel: 'Economía Máxima',
    cost: { gold: 5000, wood: 10, ore: 10 },
    heroActions: [
      'Construye la Tesorería para sumar +2.000 de oro al día adicionales.',
      'El segundo héroe consolida minas en el cuadrante conquistado.',
    ],
    combatTactic: 'Garantiza fondos ilimitados para la adquisición total de tropas en el segundo mes.',
    criticalTip: 'Arboleda alcanza ingresos superiores a 7.000 de oro al día sumando Palacio, Banco y Tesorería.',
    priority: 'Alta',
  },
  {
    day: 26,
    month: 1,
    week: 4,
    title: 'Día 26: Mejora de Tier 3 - Círculo de Menhires Mejorado (Iriyads de Espinas vs Celestiales)',
    building: 'Círculo de Menhires Mejorado',
    buildingTierLevel: 'Tier 3 Mejorado • Coste: 2.500 Oro, 5 Madera, 2 Gemas, 20 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Iriyad de Espinas (Enredo Letal en Área & Espinas Venenosas)',
      alternativeOption: 'Rama B: Iriyad Celestial (Aura Sagrada de Purificación & Gran Agilidad)',
      reason: 'La Iriyad de Espinas inmoviliza a múltiples enemigos a la vez permitiendo que los arqueros los eliminen.',
    },
    cost: { gold: 2500, wood: 5, gems: 2, alchemicalDust: 20 },
    heroActions: [
      'Mejora a todas las Iriyads para maximizar el control de raíces en combate.',
      'Limpia criptas mayores y puestos de guardia.',
    ],
    combatTactic: 'Enraíza a los atacantes pesados enemigos en el primer turno para neutralizar su avance.',
    criticalTip: 'Control absoluto del tempo de combate en la cuadrícula hexagonal.',
    priority: 'Alta',
  },
  {
    day: 27,
    month: 1,
    week: 4,
    title: 'Día 27: Comerciante de Artefactos de la Naturaleza (Artifact Merchant)',
    building: 'Comerciante de Artefactos (Artifact Merchant)',
    buildingTierLevel: 'Equipamiento de Héroe',
    cost: { gold: 2000, wood: 5, ore: 5 },
    heroActions: [
      'Equipa al comandante principal con reliquias que potencien Poder de Hechizo, Iniciativa y Moral.',
      'Vende artefactos sobrantes para acumular gemas y cristal.',
    ],
    combatTactic: 'Un héroe con estadísticas elevadas multiplica el impacto de los Fénix y Qilins en cada turno.',
    criticalTip: 'Optimiza el equipamiento antes de la transición al segundo mes.',
    priority: 'Media',
  },
  {
    day: 28,
    month: 1,
    week: 4,
    title: 'Día 28: Círculo de Druidas Primigenios (Estructura Única de Arboleda)',
    building: 'Círculo de Druidas Primigenios',
    buildingTierLevel: 'Estructura Exclusiva de Facción',
    cost: { gold: 5000, wood: 10, gems: 5, crystal: 5 },
    heroActions: [
      'Construye el Círculo de Druidas para otorgar regeneración pasiva y resistencia mágica a todas las tropas.',
      'Reúne las fuerzas para la gran ofensiva del Mes 2.',
    ],
    combatTactic: 'Las criaturas silvanas regeneran un 10% de su salud máxima al inicio de cada turno de combate.',
    criticalTip: 'Cierre magistral del Mes 1: todas las moradas operativas, Fénix mejorados y economía plena.',
    priority: 'Crítica',
  },
  {
    day: 29,
    month: 2,
    week: 5,
    title: 'Día 29: Mejora de Tier 2 - Semillero de Lúpulo Mejorado (Hoplitas Acorazados vs Falange Rápida)',
    building: 'Semillero de Lúpulo Mejorado',
    buildingTierLevel: 'Tier 2 Mejorado • Coste: 2.000 Oro, 5 Madera, 3 Mineral, 15 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Hoplita Acorazado (Muro de Escudos Inexpugnable & Resistencia Física)',
      alternativeOption: 'Rama B: Hoplita de Falange Rápida (Lanzas Largas & Ataque de Choque sin Represalia)',
      reason: 'El Hoplita Acorazado reduce el daño físico sufrido en un 35%, protegiendo la vanguardia.',
    },
    cost: { gold: 2000, wood: 5, ore: 3, alchemicalDust: 15 },
    heroActions: [
      'Mejora todo el contingente acumulado de Hoplitas.',
      'Reúne el ejército principal para avanzar sobre la cordillera central.',
    ],
    combatTactic: 'Forma una línea defensiva con los Hoplitas Acorazados protegiendo a los tiradores Faunos.',
    criticalTip: 'La infantería más resistente de Jadame en relación a su coste.',
    priority: 'Alta',
  },
  {
    day: 30,
    month: 2,
    week: 5,
    title: 'Día 30: Santuario de la Flora Silvana (+20% Resistencia Mágica Global)',
    building: 'Santuario de la Flora Silvana',
    buildingTierLevel: 'Protección Mágica de Facción',
    cost: { gold: 3000, wood: 5, gems: 3 },
    heroActions: [
      'Construye el Santuario para otorgar a todo el ejército un +20% de resistencia a todos los hechizos enemigos.',
      'El ejército principal inicia el avance hacia el territorio rival.',
    ],
    combatTactic: 'Anula la efectividad de proyectiles mágicos y hechizos de daño directo del enemigo.',
    criticalTip: 'Protección indispensable contra facciones con alta hechicería como Mazmorra o Cisma.',
    priority: 'Alta',
  },
  {
    day: 31,
    month: 2,
    week: 5,
    title: 'Día 31: Cofradía de Magos Silvana Nivel 4 (Cataclismo Solar y Raíces Vivas)',
    building: 'Cofradía de Magos Nivel 4',
    buildingTierLevel: 'Magia Maestra',
    cost: { gold: 4000, wood: 5, ore: 5, gems: 6, crystal: 6 },
    heroActions: [
      'Aprende hechizos de nivel 4: Resurrección de la Naturaleza, Juicio Solar y Enredo Masivo.',
      'El héroe principal alcanza nivel 14-16.',
    ],
    combatTactic: 'Lanza Enredo Masivo para paralizar a la totalidad del ejército rival en el turno inicial.',
    criticalTip: 'Control de batalla supremo que decide combates antes de que el enemigo pueda moverse.',
    priority: 'Alta',
  },
  {
    day: 32,
    month: 2,
    week: 5,
    title: 'Día 32: Árbol Sagrado de la Vida (+25% Crecimiento Silvano)',
    building: 'Árbol Sagrado de la Vida',
    buildingTierLevel: 'Crecimiento de Criaturas',
    cost: { gold: 4000, wood: 10, gems: 4 },
    heroActions: [
      'Construye el Árbol Sagrado para incrementar el crecimiento semanal de todas las moradas en +25%.',
      'El héroe secundario asegura la logística de transporte de tropas al frente.',
    ],
    combatTactic: 'Garantiza una reposición ininterrumpida de Fénix, Qilins y Herbomantes.',
    criticalTip: 'Multiplica la masa de tropas silvanas superando con holgura a las facciones enemigas.',
    priority: 'Alta',
  },
  {
    day: 33,
    month: 2,
    week: 5,
    title: 'Día 33: Observatorio Druídico (+1 Polvo Alquímico Diario Adicional)',
    building: 'Observatorio Druídico',
    buildingTierLevel: 'Economía Alquímica • Coste: 3.000 Oro, 4 Cristal, 25 Polvo Alquímico',
    cost: { gold: 3000, crystal: 4, alchemicalDust: 25 },
    heroActions: [
      'Amplía la generación de polvo alquímico para financiar las mejoras en el segundo bastión.',
      'Permite investigar todas las leyes astronómicas de máximo rango.',
    ],
    combatTactic: 'El polvo alquímico garantiza que cada morada capturada se mejore de inmediato.',
    criticalTip: 'Soporte vital para la hegemonía tecnológica en la recta final.',
    priority: 'Media',
  },
  {
    day: 34,
    month: 2,
    week: 5,
    title: 'Día 34: Bastión Arbóreo Exterior (Torreón Defensivo de Frontera)',
    building: 'Bastión Arbóreo Exterior',
    buildingTierLevel: 'Defensa Territorial',
    cost: { gold: 3000, wood: 10 },
    heroActions: [
      'Fortifica el paso clave que comunica tu territorio con la región central.',
      'El ejército principal sitia el primer bastión enemigo.',
    ],
    combatTactic: 'Repele incursiones secundarias enemigas protegiendo tus minas y aserraderos.',
    criticalTip: 'Seguridad absoluta en la retaguardia mientras tu fuerza de élite avanza.',
    priority: 'Media',
  },
  {
    day: 35,
    month: 2,
    week: 5,
    title: 'Día 35: Almacén de Cristal Botánico (Refinería Silvana)',
    building: 'Almacén de Cristal Botánico',
    buildingTierLevel: 'Conversión de Recursos Raros',
    cost: { gold: 4000, wood: 5, crystal: 4, gems: 4 },
    heroActions: [
      'Construye la refinería para convertir excedentes de madera en Cristal y Gemas a tasas favorables.',
      'Recluta un contingente fresco de Fénix y Qilins.',
    ],
    combatTactic: 'Garantiza reservas ilimitadas de los dos recursos mágicos primarios de Arboleda.',
    criticalTip: 'Autonomía total en recursos mágicos para la fase de expansión agresiva.',
    priority: 'Alta',
  },
  {
    day: 36,
    month: 2,
    week: 6,
    title: 'Día 36: Asentamiento Silvano Secundario (Town Hall en Ciudad Capturada)',
    building: 'Asentamiento Silvano Secundario (Town Hall)',
    buildingTierLevel: 'Expansión Territorial',
    cost: { gold: 2500 },
    heroActions: [
      'Convierte el asentamiento recién capturado en una base silvana totalmente funcional.',
      'Recluta un héroe de apoyo para vigilar el flanco oriental.',
    ],
    combatTactic: 'Permite reclutar y reforzar tropas en el corazón del territorio rival.',
    criticalTip: 'Suma +1.000 de oro al día y expande tu presencia territorial.',
    priority: 'Alta',
  },
  {
    day: 37,
    month: 2,
    week: 6,
    title: 'Día 37: Raíces Viajeras de Jadame (Red de Transporte Arbóreo Regional)',
    building: 'Raíces Viajeras de Jadame',
    buildingTierLevel: 'Movilidad Estratégica',
    cost: { gold: 5000, wood: 10, crystal: 5 },
    heroActions: [
      'Activa la red de raíces para teletransportar héroes y tropas entre las dos ciudades.',
      'El comandante principal se desplaza al instante para responder a cualquier amenaza.',
    ],
    combatTactic: 'Movilidad estratégica instantánea sin consumo de puntos de movimiento.',
    criticalTip: 'Descoloca la estrategia enemiga permitiendo ataques en múltiples frentes simultáneos.',
    priority: 'Crítica',
  },
  {
    day: 38,
    month: 2,
    week: 6,
    title: 'Día 38: Fortificaciones del Segundo Claro (Fortifications I)',
    building: 'Fortificaciones del Segundo Claro',
    buildingTierLevel: 'Defensa de Base Avanzada',
    cost: { gold: 2500, wood: 5, ore: 5 },
    heroActions: [
      'Construye murallas y torreones en el asentamiento secundario.',
      'El ejército principal continúa su avance hacia la capital enemiga.',
    ],
    combatTactic: 'Protege tu base de operaciones avanzada contra ataques relámpago rivales.',
    criticalTip: 'Guarnición segura para almacenar tropas de reemplazo.',
    priority: 'Media',
  },
  {
    day: 39,
    month: 2,
    week: 6,
    title: 'Día 39: Segundo Círculo de Menhires (Iriyads Secundarias)',
    building: 'Segundo Círculo de Menhires',
    buildingTierLevel: 'Producción Militar Adicional',
    cost: { gold: 1500, wood: 5, ore: 5 },
    heroActions: [
      'Añade una morada de Iriyads en la base avanzada para duplicar su reclutamiento semanal.',
      'Limpia tesoros neutrales restantes en el cuadrante norte.',
    ],
    combatTactic: 'Genera escuadras de control de raíces directamente en la línea de frente.',
    criticalTip: 'Mayor masa de control para las batallas de asedio.',
    priority: 'Alta',
  },
  {
    day: 40,
    month: 2,
    week: 6,
    title: 'Día 40: Segunda Choza de Herbomantes (Shroomwood Shack Secundario)',
    building: 'Segunda Choza de Herbomantes',
    buildingTierLevel: 'Producción Militar Tier 5 Adicional',
    cost: { gold: 3000, wood: 5, gems: 3 },
    heroActions: [
      'Construye una morada de Herbomantes secundaria para duplicar el soporte mágico del ejército.',
      'El héroe principal asalta el segundo bastión enemigo.',
    ],
    combatTactic: 'Doble contingente de lanzadores de esporas fúngicas debilitantes.',
    criticalTip: 'Soporte mágico masivo para neutralizar la ventaja numérica enemiga.',
    priority: 'Alta',
  },
  {
    day: 41,
    month: 2,
    week: 6,
    title: 'Día 41: Ciudadela Silvana de la Segunda Base (+50% Crecimiento Secundario)',
    building: 'Ciudadela Silvana (Citadel)',
    buildingTierLevel: 'Crecimiento Militar Secundario',
    cost: { gold: 2500, ore: 10 },
    heroActions: [
      'Incrementa el crecimiento de la base avanzada en un +50%.',
      'Prepara los recursos para erigir la segunda Pira de Fénix.',
    ],
    combatTactic: 'Afluencia masiva de refuerzos listos para la batalla final de la Semana 7.',
    criticalTip: 'Multiplica la tasa de reclutamiento en territorio hostil.',
    priority: 'Alta',
  },
  {
    day: 42,
    month: 2,
    week: 6,
    title: 'Día 42: Segunda Pira de Fénix (Tier 7 Secundario de Arboleda)',
    building: 'Segunda Pira (Pyre)',
    buildingTierLevel: 'Producción Militar Tier 7 Adicional',
    cost: { gold: 10000, wood: 15, crystal: 10, gems: 10 },
    heroActions: [
      'Construye la segunda Pira para duplicar la producción semanal de Fénix.',
      'Recluta un contingente adicional de Fénix para equipar al segundo ejército de asalto.',
    ],
    combatTactic: 'Dos ejércitos con Fénix operando en tenaza sobre las últimas posiciones del enemigo.',
    criticalTip: 'Tener dos moradas de Fénix activas consagra la supremacía militar absoluta.',
    priority: 'Crítica',
  },
  {
    day: 43,
    month: 2,
    week: 7,
    title: 'Día 43: Cofradía de Magos Silvana Nivel 5 (Resurrección de Gaia y Lluvia Solar)',
    building: 'Cofradía de Magos Nivel 5',
    buildingTierLevel: 'Magia Divina / Silvana Suprema',
    cost: { gold: 5000, wood: 5, ore: 5, gems: 8, crystal: 8 },
    heroActions: [
      'Aprende hechizos supremos de nivel 5: Resurrección Masiva, Ira de Gaia y Vuelo Místico.',
      'El héroe principal domina la totalidad del conocimiento mágico silvano.',
    ],
    combatTactic: 'Resucita a todas las tropas caídas al final del combate garantizando cero bajas.',
    criticalTip: 'La maestría mágica silvana anula cualquier posibilidad de derrota por desgaste.',
    priority: 'Crítica',
  },
  {
    day: 44,
    month: 2,
    week: 7,
    title: 'Día 44: Trono de los Fénix (+2 Moral y +2 Suerte a Criaturas Silvanas)',
    building: 'Trono de los Fénix (Monumento Supremo)',
    buildingTierLevel: 'Monumento de Facción',
    cost: { gold: 6000, crystal: 6, gems: 6 },
    heroActions: [
      'Erige el Trono de los Fénix para conferir +2 de Moral y +2 de Suerte permanentes a todas tus tropas.',
      'El ejército principal inicia la marcha definitiva hacia la capital rival.',
    ],
    combatTactic: 'Tasa constante de golpes críticos afortunados y turnos adicionales por moral divina.',
    criticalTip: 'Multiplica la efectividad de cada unidad silvana en el combate final.',
    priority: 'Alta',
  },
  {
    day: 45,
    month: 2,
    week: 7,
    title: 'Día 45: Segundo Silo de Recursos Regional (+1 Gema y +1 Cristal Adicionales)',
    building: 'Segundo Silo de Recursos',
    buildingTierLevel: 'Economía Regional',
    cost: { gold: 0, gems: 3, crystal: 3 },
    heroActions: [
      'Añade un segundo silo para duplicar la renta pasiva a +2 Gemas y +2 Cristales al día.',
      'El héroe secundario asegura los corredores de abastecimiento.',
    ],
    combatTactic: 'Recursos mágicos ilimitados para costear los hechizos de nivel 5 en cada combate.',
    criticalTip: 'Elimina cualquier restricción económica para las dos semanas finales.',
    priority: 'Media',
  },
  {
    day: 46,
    month: 2,
    week: 7,
    title: 'Día 46: Mejora de Segunda Pira de Fénix (Fénix de Luz Adicionales)',
    building: 'Segunda Pira Mejorada',
    buildingTierLevel: 'Tier 7 Mejorado Secundario • Coste: 8.000 Oro, 10 Madera, 8 Cristal, 8 Gemas, 100 Polvo Alquímico',
    cost: { gold: 8000, wood: 10, crystal: 8, gems: 8, alchemicalDust: 100 },
    heroActions: [
      'Mejora la segunda Pira para reclutar Fénix de Luz de élite en ambos ejércitos.',
      'Equipa a ambos comandantes con la flor y nata del ejército silvano.',
    ],
    combatTactic: 'Despliega Fénix de Luz en ambas alas para arrasar las formaciones defensivas del rival.',
    criticalTip: 'Dos contingentes completos de Tier 7 de élite con renacimiento garantizado.',
    priority: 'Crítica',
  },
  {
    day: 47,
    month: 2,
    week: 7,
    title: 'Día 47: Corona del Dosel del Bosque (Visión Total de la Naturaleza en Jadame)',
    building: 'Corona del Dosel del Bosque',
    buildingTierLevel: 'Información y Exploración Total',
    cost: { gold: 5000, wood: 10, gems: 5 },
    heroActions: [
      'Extiende la red arbórea para revelar la totalidad del mapa de Jadame sin niebla de guerra.',
      'Localiza la ubicación exacta de los ejércitos enemigos restantes.',
    ],
    combatTactic: 'Elige el ángulo de ataque perfecto emboscando a los héroes enemigos.',
    criticalTip: 'Visión completa para asestar el golpe de gracia a las fuerzas rivales.',
    priority: 'Alta',
  },
  {
    day: 48,
    month: 2,
    week: 7,
    title: 'Día 48: Corazón de Jadame (+15% Daño Mágico de Luz y Naturaleza)',
    building: 'Corazón de Jadame',
    buildingTierLevel: 'Potenciador Arcano de Facción',
    cost: { gold: 4000, gems: 6, crystal: 6 },
    heroActions: [
      'Construye el Corazón de Jadame para incrementar en un +15% el daño de toda la magia de Luz y Naturaleza.',
      'El héroe principal maximiza su reserva de maná.',
    ],
    combatTactic: 'Destruye pilas enemigas completas de un solo conjuro de Juicio Solar o Ira de Gaia.',
    criticalTip: 'Poder de devastación mágico insuperable para el asedio final.',
    priority: 'Alta',
  },
  {
    day: 49,
    month: 2,
    week: 7,
    title: 'Día 49: Granero Sagrado de Semillas (Optimización de Suministros)',
    building: 'Granero Sagrado de Semillas',
    buildingTierLevel: 'Optimización Logística',
    cost: { gold: 3500, wood: 10 },
    heroActions: [
      'Almacena reservas para financiar la compra masiva de tropas del último lunes de la campaña.',
      'Los exploradores se sitúan frente a las puertas de la última capital enemiga.',
    ],
    combatTactic: 'Concentra la totalidad del inventario de oro en la compra de la hueste definitiva.',
    criticalTip: 'Prepara el último gran día de compras militares del Día 50.',
    priority: 'Media',
  },
  {
    day: 50,
    month: 2,
    week: 8,
    title: 'Día 50: Forja Silvana de Gaia (Balistas Sagradas y Catapultas de Rocas Vivas)',
    building: 'Forja Silvana de Gaia',
    buildingTierLevel: 'Maquinaria de Guerra',
    cost: { gold: 3000, wood: 10, ore: 5 },
    heroActions: [
      'Construye catapultas vivas y balistas para el asedio definitivo.',
      'El ejército principal toma posiciones ante la capital del último oponente.',
    ],
    combatTactic: 'La catapulta derriba murallas en el primer asalto permitiendo la entrada directa de Fénix y Qilins.',
    criticalTip: 'Anula las fortificaciones enemigas sin sufrir desgaste de torres defensivas.',
    priority: 'Alta',
  },
  {
    day: 51,
    month: 2,
    week: 8,
    title: 'Día 51: Manantial de la Eterna Primavera (+50% Capacidad de Reserva de Tropas)',
    building: 'Manantial de la Eterna Primavera',
    buildingTierLevel: 'Capacidad Máxima Militar',
    cost: { gold: 5000, wood: 10, crystal: 5, gems: 5 },
    heroActions: [
      'Expande la reserva de tropas para acumular un excedente masivo de Faunos y Hoplitas.',
      'Se finaliza el ensamblaje de la hueste de invasión de Arboleda.',
    ],
    combatTactic: 'Supera en número y calidad al adversario en todas las fases del combate.',
    criticalTip: 'Masa crítica definitiva que pulveriza cualquier defensa enemiga.',
    priority: 'Alta',
  },
  {
    day: 52,
    month: 2,
    week: 8,
    title: 'Día 52: Reclutamiento Masivo de la Hueste de Fénix y Qilins Celestes',
    building: 'Reclutamiento Supremo Silvano',
    buildingTierLevel: 'Reclutamiento Militar Final',
    cost: { gold: 12000, crystal: 10, gems: 10 },
    heroActions: [
      'Compra la totalidad de los Fénix de Luz, Qilins y Herbomantes disponibles en ambas ciudades.',
      'El ejército alcanza su cenit de poder militar en Jadame.',
    ],
    combatTactic: 'Formación hexagonal completa con Fénix en vanguardia, Qilins en flanco y Hoplitas como núcleo.',
    criticalTip: 'La mayor fuerza militar de la naturaleza jamás reunida en la historia de Jadame.',
    priority: 'Crítica',
  },
  {
    day: 53,
    month: 2,
    week: 8,
    title: 'Día 53: Muros de Zarzas Defensivas en Pasos de Montaña',
    building: 'Zarzas Defensivas de Paso',
    buildingTierLevel: 'Control Defensivo del Territorio',
    cost: { gold: 4000, wood: 10 },
    heroActions: [
      'Bloquea todos los pasos de escape con zarzas vivas impidiendo cualquier fuga del general enemigo.',
      'El rival queda sitiado en su última fortaleza.',
    ],
    combatTactic: 'Aísla al general enemigo sin posibilidad de recibir refuerzos.',
    criticalTip: 'Cierre total de las vías de escape del enemigo.',
    priority: 'Media',
  },
  {
    day: 54,
    month: 2,
    week: 8,
    title: 'Día 54: Comunión de los Espíritus del Bosque (+3 Velocidad e Iniciativa Global)',
    building: 'Altar de la Comunión Sagrada',
    buildingTierLevel: 'Bendición de Batalla',
    cost: { gold: 6000, crystal: 8, gems: 8 },
    heroActions: [
      'Canaliza la comunión de los espíritus para conferir +3 de Iniciativa y +20% de Velocidad a todo el ejército.',
      'Las tropas silvanas actúan primero en todas las rondas de combate.',
    ],
    combatTactic: 'Ataca con toda la hueste antes de que el enemigo pueda lanzar su primer hechizo o ataque.',
    criticalTip: 'Garantiza la aniquilación de la primera línea enemiga antes de que puedan reaccionar.',
    priority: 'Crítica',
  },
  {
    day: 55,
    month: 2,
    week: 8,
    title: 'Día 55: Carga Sagrada de la Hueste de Gaia hacia la Última Fortaleza Enemiga',
    building: 'Carga de Guerra Silvana',
    buildingTierLevel: 'Fase Ofensiva Final',
    cost: { gold: 5000 },
    heroActions: [
      'Inicia el asalto final a la capital enemiga con las catapultas de rocas vivas y el ejército completo.',
      'Destruye las torres de guardia exteriores.',
    ],
    combatTactic: 'Derriba las murallas mientras los Fénix eliminan a los tiradores en el interior del castillo.',
    criticalTip: 'Último asalto para la unificación pacífica de Jadame bajo el dosel del bosque.',
    priority: 'Crítica',
  },
  {
    day: 56,
    month: 2,
    week: 8,
    title: 'Día 56: Armonía Eterna de Jadame: Victoria Absoluta de la Arboleda',
    building: 'Templo del Bosque Eterno',
    buildingTierLevel: 'Consumación de la Campaña',
    cost: { gold: 15000, wood: 20, crystal: 15, gems: 15 },
    heroActions: [
      'Armonización final de todas las fortalezas y regiones de Jadame bajo el mandato de la Arboleda.',
      'Victoria total y definitiva tras 56 días de desarrollo táctico y económico impecable.',
    ],
    combatTactic: 'Fénix de Luz inmortales, Qilins celestes y legiones de Hoplitas aseguran el triunfo definitivo.',
    criticalTip: '¡Estrategia de 56 días de Arboleda completada con éxito rotundo y fidelidad canónica absoluta!',
    priority: 'Crítica',
  },
];

console.log('Arboleda steps 15-56 prepared:', arboledaDays15To56.length);

module.exports = { arboledaDays15To56 };
