const fs = require('fs');
const path = require('path');

// CISMA DAYS 15-56
const cismaDays15To56 = [
  {
    day: 15,
    month: 1,
    week: 3,
    title: 'Día 15: Tier 6 - Mansión Hinchada / Abotagada (Bloated Manor - Árbitros / Enviados Abisales)',
    building: 'Mansión Hinchada (Bloated Manor)',
    buildingTierLevel: 'Tier 6',
    cost: { gold: 5000, ore: 10, mercury: 6 },
    heroActions: [
      'Recluta Árbitros del Vacío. Colosos de las fallas con ataques pesados de hielo negro y manipulación dimensional.',
      'El héroe principal asalta el anillo medio neutral con apoyo de Enviados Abisales y Árbitros.',
    ],
    combatTactic: 'El Árbitro drena el maná y rompe las armaduras de los colosos rivales con cada impacto.',
    criticalTip: 'Aporta control de masa y daño devastador en combate cuerpo a cuerpo.',
    priority: 'Alta',
  },
  {
    day: 16,
    month: 1,
    week: 3,
    title: 'Día 16: Mercado del Vacío (Marketplace)',
    building: 'Mercado del Vacío (Marketplace)',
    buildingTierLevel: 'Comercio e Intercambio',
    cost: { gold: 500, wood: 5 },
    heroActions: [
      'Construye el Mercado para intercambiar excedentes de madera por mineral y mercurio.',
      'El explorador secundario bandera aserraderos y minas de la periferia.',
    ],
    combatTactic: 'Estabiliza el inventario de mercurio para sostener las mejoras mágicas de Semana 3 y 4.',
    criticalTip: 'Prerrequisito cívico obligatorio para el Banco del Cisma y el Silo de Recursos.',
    priority: 'Alta',
  },
  {
    day: 17,
    month: 1,
    week: 3,
    title: 'Día 17: Bóveda de las Sombras / Banco (Bank - +500 Oro/día)',
    building: 'Bóveda de las Sombras (Bank)',
    buildingTierLevel: 'Economía Avanzada',
    cost: { gold: 4000, wood: 10, ore: 10 },
    heroActions: [
      'Edifica el Banco para sumar renta pasiva de 500 de oro al día y consolidar intereses.',
      'El héroe principal limpia bancos de monstruos de alto nivel.',
    ],
    combatTactic: 'Financia las compras masivas de Titanes del Vacío y Árbitros en cada cambio de semana.',
    criticalTip: 'Garantiza liquidez permanente para la facción antes de la Metrópolis.',
    priority: 'Alta',
  },
  {
    day: 18,
    month: 1,
    week: 3,
    title: 'Día 18: Silo de Recursos (+1 Mercurio Diario para Cisma)',
    building: 'Silo de Recursos (Resource Silo)',
    buildingTierLevel: 'Estructura de Recursos Raros • Prerrequisito: Mercado y Banco',
    cost: { gold: 0, gems: 3, crystal: 3 },
    heroActions: [
      'Erige el Silo de Recursos para iniciar la producción pasiva de +1 Mercurio al día.',
      'El mercurio es el recurso mágico fundamental de Cisma para ritos de invocación, Concubis y Titanes.',
    ],
    combatTactic: 'El suministro diario de mercurio elimina cuellos de botella para las tropas superiores.',
    criticalTip: 'En Cisma el Silo de Recursos genera +1 Mercurio diario. Coste de construcción 0 Oro.',
    priority: 'Alta',
  },
  {
    day: 19,
    month: 1,
    week: 3,
    title: 'Día 19: Silo Alquímico (Generador Diario de Polvo Alquímico)',
    building: 'Silo Alquímico (Alchemic Silo)',
    buildingTierLevel: 'Generador de Recursos Mágicos • Prerrequisito: Silo de Recursos',
    cost: { gold: 2000, ore: 5, mercury: 2, alchemicalDust: 25 },
    heroActions: [
      'Construye el Silo Alquímico para generar Polvo Alquímico imprescindible para mejorar moradas.',
      'El héroe principal avanza hacia el paso fronterizo del rival.',
    ],
    combatTactic: 'El polvo alquímico permite financiar los 100 de polvo requeridos para la mejora de Tier 7.',
    criticalTip: 'Imprescindible para costear las mejoras de Tiers 1 a 7 con ramas duales.',
    priority: 'Alta',
  },
  {
    day: 20,
    month: 1,
    week: 3,
    title: 'Día 20: Remanente Abisal III (Metropolis - +4.000 Oro/día)',
    building: 'Remanente Abisal III (Metropolis)',
    buildingTierLevel: 'Economía Máxima',
    cost: { gold: 10000, wood: 10, ore: 10 },
    heroActions: [
      'Alcanza el estatus de Metrópolis en Cisma para consolidar 4.000 de oro al día.',
      'El ejército principal se reagrupa listo para la gran mejora de Tier 7 en Día 21.',
    ],
    combatTactic: 'Sustenta la compra del 100% del contingente semanal de todas las moradas.',
    criticalTip: 'Supremacía económica absoluta antes de la gran mejora de Tier 7.',
    priority: 'Crítica',
  },
  {
    day: 21,
    month: 1,
    week: 3,
    title: 'Día 21: Mejora de Tier 7 - Santuario del Abismo Mejorado (Titán del Vacío vs Devorador Cósmico)',
    building: 'Santuario del Abismo Mejorado',
    buildingTierLevel: 'Tier 7 Mejorado • Coste: 8.000 Oro, 10 Mineral, 8 Mercurio, 100 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Titán del Vacío (Inmunidad Mágica Absoluta & Voluntad del Abismo - Doble Turno)',
      alternativeOption: 'Rama B: Devorador Cósmico (Agujero Negro en Área & Drenaje de Maná Masivo)',
      reason: 'El Titán del Vacío actúa dos veces seguidas en su primera ronda e ignora todos los hechizos enemigos.',
    },
    cost: { gold: 8000, ore: 10, mercury: 8, alchemicalDust: 100 },
    heroActions: [
      'Mejora el Santuario del Abismo para reclutar Titanes del Vacío / Devoradores Cósmicos.',
      'Asalta fortalezas enemigas con la supremacía de Tier 7 de élite.',
    ],
    combatTactic: 'El Titán del Vacío ejecuta su doble turno inicial para aniquilar la pieza clave del adversario.',
    criticalTip: 'Con Tier 7 mejorado en Día 21, el Cisma domina el campo táctico con ventaja indiscutible.',
    priority: 'Crítica',
  },
  {
    day: 22,
    month: 1,
    week: 4,
    title: 'Día 22: Mejora de Tier 6 - Mansión Hinchada Mejorada (Árbitros Mayores vs Enviados de la Falla)',
    building: 'Mansión Hinchada Mejorada',
    buildingTierLevel: 'Tier 6 Mejorado • Coste: 5.000 Oro, 10 Mineral, 4 Mercurio, 50 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Árbitro Mayor (Golpe de Vacío Aniquilador & Ruptura de Blindaje)',
      alternativeOption: 'Rama B: Enviado de la Falla (Teletransporte Táctico & Congelación de Vori)',
      reason: 'El Árbitro Mayor reduce a cero la armadura de su objetivo, multiplicando el daño del ejército.',
    },
    cost: { gold: 5000, ore: 10, mercury: 4, alchemicalDust: 50 },
    heroActions: [
      'Mejora la Mansión para incorporar Árbitros Mayores.',
      'El ejército principal abre brecha en el territorio enemigo.',
    ],
    combatTactic: 'Combina la anulación de armadura del Árbitro Mayor con las descargas de los Titanes del Vacío.',
    criticalTip: 'Potencia de perforación masiva contra unidades ultrablindadas.',
    priority: 'Alta',
  },
  {
    day: 23,
    month: 1,
    week: 4,
    title: 'Día 23: Cofradía de Magos del Cisma Nivel 3 (Magia Arcana y Escarcha de Vori)',
    building: 'Cofradía de Magos Nivel 3',
    buildingTierLevel: 'Magia de Alto Nivel',
    cost: { gold: 3000, wood: 5, ore: 5, mercury: 4 },
    heroActions: [
      'Aprende hechizos de nivel 3: Ventisca de Vori, Distorsión Espaciotemporal y Escudo del Vacío.',
      'El héroe principal asalta el anillo exterior del oponente.',
    ],
    combatTactic: 'Lanza Ventisca de Vori para ralentizar e inmovilizar a toda la infantería rival.',
    criticalTip: 'Sinergia brutal con la gran velocidad de Jinetes Aga\'Shoth y Shoths.',
    priority: 'Alta',
  },
  {
    day: 24,
    month: 1,
    week: 4,
    title: 'Día 24: Mejora de Tier 5 - Casa de las Cadenas Mejorada (Señoras de las Cadenas vs Hechiceras)',
    building: 'Casa de las Cadenas Mejorada',
    buildingTierLevel: 'Tier 5 Mejorado • Coste: 4.000 Oro, 5 Mineral, 4 Mercurio, 35 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Señora de las Cadenas (Control Mental Temporal & Latigazo de Falla)',
      alternativeOption: 'Rama B: Hechicera del Vacío (Drenaje de Maná en Área & Maldición de Fragilidad)',
      reason: 'La Señora de las Cadenas toma el control de una escuadra enemiga en el primer turno de combate.',
    },
    cost: { gold: 4000, ore: 5, mercury: 4, alchemicalDust: 35 },
    heroActions: [
      'Mejora a las Concubis a Señoras de las Cadenas.',
      'Captura la primera ciudad satélite o puesto de avanzada enemigo.',
    ],
    combatTactic: 'Controla a los tiradores o caballería enemiga para que ataquen a sus propios aliados.',
    criticalTip: 'Habilidad de subversión táctica decisiva en batallas contra generales enemigos.',
    priority: 'Alta',
  },
  {
    day: 25,
    month: 1,
    week: 4,
    title: 'Día 25: Tesoro Abisal (Treasury - +2.000 Oro/día)',
    building: 'Tesoro Abisal (Treasury)',
    buildingTierLevel: 'Economía Máxima',
    cost: { gold: 5000, wood: 10, ore: 10 },
    heroActions: [
      'Construye la Tesorería para sumar +2.000 de oro al día adicionales.',
      'El segundo héroe consolida minas en el cuadrante conquistado.',
    ],
    combatTactic: 'Garantiza fondos infinitos para sostener el reclutamiento total en el segundo mes.',
    criticalTip: 'El Cisma alcanza ingresos de más de 7.000 oro diarios sumando Asentamiento, Banco y Tesorería.',
    priority: 'Alta',
  },
  {
    day: 26,
    month: 1,
    week: 4,
    title: 'Día 26: Mejora de Tier 4 - Rito Inquietante Mejorado (Grandes Shoths Corrosivos vs Devastadores)',
    building: 'Rito Inquietante de Invocación Mejorado',
    buildingTierLevel: 'Tier 4 Mejorado • Coste: 3.000 Oro, 5 Mineral, 3 Mercurio, 25 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Gran Shoth Corrosivo (Vuelo de Falla, Supresión de Enfoque & Escarcha)',
      alternativeOption: 'Rama B: Gran Shoth Devastador (Rito de Invocación Duplicado & Daño Mágico Masivo)',
      reason: 'El Gran Shoth Corrosivo vuela sobre murallas y anula la generación de Enfoque de los colosos rivales.',
    },
    cost: { gold: 3000, ore: 5, mercury: 3, alchemicalDust: 25 },
    heroActions: [
      'Mejora a los Grandes Shoths para potenciar el hostigamiento aéreo.',
      'Limpia puestos fronterizos y campamentos de artefactos.',
    ],
    combatTactic: 'Despliega a los Grandes Shoths para bloquear tiradores en Turno 1 sin riesgo.',
    criticalTip: 'Criatura voladora con gran movilidad para asedios de fortalezas.',
    priority: 'Alta',
  },
  {
    day: 27,
    month: 1,
    week: 4,
    title: 'Día 27: Comerciante de Reliquias de la Falla (Artifact Merchant)',
    building: 'Comerciante de Reliquias (Artifact Merchant)',
    buildingTierLevel: 'Equipamiento de Héroe',
    cost: { gold: 2000, wood: 5, ore: 5 },
    heroActions: [
      'Equipa al comandante principal con artefactos que potencien Sabiduría, Maná y Poder de Hechizo.',
      'Vende reliquias no afines para acumular mercurio y gemas.',
    ],
    combatTactic: 'Un héroe con estadísticas arcanas elevadas potencia los ritos de invocación permanente.',
    criticalTip: 'Optimiza las estadísticas antes del inicio del segundo mes.',
    priority: 'Media',
  },
  {
    day: 28,
    month: 1,
    week: 4,
    title: 'Día 28: Círculo de la Comunión Abisal (Estructura Única de Cisma)',
    building: 'Círculo de la Comunión Abisal',
    buildingTierLevel: 'Estructura Exclusiva de Facción',
    cost: { gold: 5000, ore: 10, mercury: 5 },
    heroActions: [
      'Construye el Círculo de Comunión para incrementar un +25% las tropas invocadas mediante demonología y ritos.',
      'Prepara el ejército para la gran ofensiva de la Semana 5.',
    ],
    combatTactic: 'Cada baja enemiga o aliada produce más tropas permanentes al término del combate.',
    criticalTip: 'Cierre magistral del Mes 1: todas las moradas activas, Tier 7 mejorado y economía colosal.',
    priority: 'Crítica',
  },
  {
    day: 29,
    month: 2,
    week: 5,
    title: 'Día 29: Mejora de Tier 3 - Establos de Aga\'Shoth Mejorados (Jinetes del Vacío vs Destructores)',
    building: 'Establos de Aga\'Shoth Mejorados',
    buildingTierLevel: 'Tier 3 Mejorado • Coste: 2.500 Oro, 5 Mineral, 2 Mercurio, 20 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Jinete del Vacío (Carga Dimensional sin Represalia & Gran Velocidad)',
      alternativeOption: 'Rama B: Destructor Aga\'Shoth (Embestida Brutal & Ruptura de Formación)',
      reason: 'El Jinete del Vacío cruza el mapa táctico y golpea sin recibir contraataque.',
    },
    cost: { gold: 2500, ore: 5, mercury: 2, alchemicalDust: 20 },
    heroActions: [
      'Mejora todo el contingente acumulado de Jinetes Aga\'Shoth.',
      'Reúne las hordas del nuevo mes en el héroe principal.',
    ],
    combatTactic: 'Lanza a los Jinetes del Vacío en Turno 1 contra los hechiceros o tiradores rivales.',
    criticalTip: 'Caballería de choque de primer orden en relación a su coste.',
    priority: 'Alta',
  },
  {
    day: 30,
    month: 2,
    week: 5,
    title: 'Día 30: Mejora de Tier 1 - Rito Menor de Invocación Mejorado (Ra\'Shoths Voraces vs Glaciales)',
    building: 'Rito Menor Mejorado (Ra\'Shoths de Élite)',
    buildingTierLevel: 'Tier 1 Mejorado • Coste: 2.000 Oro, 5 Mineral, 10 Polvo Alquímico',
    buildingChoice: {
      type: 'Mejora de Unidad (Rama A vs B)',
      recommendedOption: 'Rama A: Ra\'Shoth Voraz (Rito de Invocación Duplicado & Consunción de Salud)',
      alternativeOption: 'Rama B: Ra\'Shoth Glacial (Aura de Escarcha de Vori & Ralentización)',
      reason: 'El Ra\'Shoth Voraz multiplica la masa de criaturas permanentes generadas en cada escaramuza.',
    },
    cost: { gold: 2000, ore: 5, alchemicalDust: 10 },
    heroActions: [
      'Actualiza las miles de unidades de Ra\'Shoths para su uso en asedios masivos.',
      'El ejército principal cruza el paso helado hacia la capital rival.',
    ],
    combatTactic: 'Usa a los Ra\'Shoths Voraces como vanguardia sacrificial para engrosar tu ejército gratis.',
    criticalTip: 'Con todas las moradas mejoradas, el Cisma es imparable.',
    priority: 'Alta',
  },
  {
    day: 31,
    month: 2,
    week: 5,
    title: 'Día 31: Cofradía de Magos del Cisma Nivel 4 (Hechizos de Vacío y Cero Absoluto)',
    building: 'Cofradía de Magos Nivel 4',
    buildingTierLevel: 'Magia Maestra',
    cost: { gold: 4000, wood: 5, ore: 5, mercury: 8 },
    heroActions: [
      'Aprende hechizos de nivel 4: Ruptura Dimensional, Congelación Absoluta y Agujero de Falla.',
      'El comandante principal alcanza nivel 14-16.',
    ],
    combatTactic: 'Lanza Ruptura Dimensional para teleportar unidades pesadas al corazón de la defensa rival.',
    criticalTip: 'Los hechizos de nivel 4 destruyen fortificaciones y diezman ejércitos acampados.',
    priority: 'Alta',
  },
  {
    day: 32,
    month: 2,
    week: 5,
    title: 'Día 32: Falla de Invocación Acelerada (+25% Crecimiento de Criaturas del Vacío)',
    building: 'Falla de Invocación Acelerada',
    buildingTierLevel: 'Crecimiento de Criaturas',
    cost: { gold: 4000, ore: 10, mercury: 4 },
    heroActions: [
      'Construye la Falla para incrementar el crecimiento semanal de todas las moradas en +25%.',
      'El héroe secundario asegura la cadena de refuerzos hacia el frente.',
    ],
    combatTactic: 'Aumenta el flujo de reclutamiento para reponer cualquier pérdida instantáneamente.',
    criticalTip: 'Suma acumulación de criaturas masiva que desborda al rival.',
    priority: 'Alta',
  },
  {
    day: 33,
    month: 2,
    week: 5,
    title: 'Día 33: Observatorio del Vacío (+1 Polvo Alquímico Diario Adicional)',
    building: 'Observatorio del Vacío',
    buildingTierLevel: 'Economía Alquímica • Coste: 3.000 Oro, 4 Mercurio, 25 Polvo Alquímico',
    cost: { gold: 3000, mercury: 4, alchemicalDust: 25 },
    heroActions: [
      'Amplía las instalaciones alquímicas para duplicar la producción diaria de Polvo.',
      'Permite financiar mejoras en ciudades capturadas y tecnologías astrales.',
    ],
    combatTactic: 'El polvo constante financia el Observatorio y las leyes de máximo rango.',
    criticalTip: 'Soporte fundamental para la dominación tecnológica del segundo mes.',
    priority: 'Media',
  },
  {
    day: 34,
    month: 2,
    week: 5,
    title: 'Día 34: Ciudadela de Hielo Negro Exterior (Torreón Defensivo de Frontera)',
    building: 'Ciudadela de Hielo Negro',
    buildingTierLevel: 'Defensa Territorial',
    cost: { gold: 3000, ore: 10 },
    heroActions: [
      'Fortifica el paso clave que conecta los valles de Vori con las tierras bajas de Jadame.',
      'El ejército principal inicia el cerco sobre el primer bastión enemigo.',
    ],
    combatTactic: 'El torreón repele incursiones secundarias del rival sin distraer al ejército central.',
    criticalTip: 'Asegura tu retaguardia mientras tu fuerza principal opera en territorio enemigo.',
    priority: 'Media',
  },
  {
    day: 35,
    month: 2,
    week: 5,
    title: 'Día 35: Condensador de Mercurio de la Falla (Conversión Eficiente de Recursos)',
    building: 'Condensador de Mercurio',
    buildingTierLevel: 'Conversión de Recursos Raros',
    cost: { gold: 4000, ore: 5, mercury: 4 },
    heroActions: [
      'Edifica el Condensador para convertir excedentes de mineral en Mercurio a una tasa óptima.',
      'Recluta un contingente fresco de Titanes del Vacío y Árbitros.',
    ],
    combatTactic: 'Garantiza que nunca falte Mercurio para hechizos y reclutamiento de alto nivel.',
    criticalTip: 'Autosuficiencia en el recurso más crítico de la facción.',
    priority: 'Alta',
  },
  {
    day: 36,
    month: 2,
    week: 6,
    title: 'Día 36: Asentamiento del Cisma Secundario (Town Hall en Ciudad Capturada)',
    building: 'Asentamiento del Cisma Secundario (Town Hall)',
    buildingTierLevel: 'Expansión Territorial',
    cost: { gold: 2500 },
    heroActions: [
      'Reconstruye la sede cívica de la ciudad recién conquistada para convertirla en nodo del vacío.',
      'Establece guarnición con tropas de tiers intermedios.',
    ],
    combatTactic: 'La ciudad capturada se convierte en un centro logístico avanzado en territorio rival.',
    criticalTip: 'Genera +1.000 de oro al día y permite reclutar héroes en el frente de batalla.',
    priority: 'Alta',
  },
  {
    day: 37,
    month: 2,
    week: 6,
    title: 'Día 37: Vórtice Dimensional Regional (Teletransporte de Tropas entre Bases)',
    building: 'Vórtice Dimensional Regional',
    buildingTierLevel: 'Movilidad Estratégica',
    cost: { gold: 5000, ore: 10, mercury: 5 },
    heroActions: [
      'Abre la brecha interdimensional que conecta la capital con la ciudad secundaria.',
      'El héroe principal se desplaza al instante entre bases reforzando ambos frentes.',
    ],
    combatTactic: 'Permite transferir tropas sin consumir puntos de movimiento en el mapa de aventura.',
    criticalTip: 'Movilidad estratégica insuperable que descoloca la defensa enemiga.',
    priority: 'Crítica',
  },
  {
    day: 38,
    month: 2,
    week: 6,
    title: 'Día 38: Fortificaciones de la Segunda Falla (Fortifications I)',
    building: 'Fortificaciones de la Segunda Falla',
    buildingTierLevel: 'Defensa de Base Avanzada',
    cost: { gold: 2500, ore: 5 },
    heroActions: [
      'Erige murallas defensivas en el asentamiento secundario.',
      'El explorador patrulla las rutas de escape del rival.',
    ],
    combatTactic: 'Impide contraofensivas relámpago contra tu base de suministro.',
    criticalTip: 'Base fortificada segura para acopiar tropas recién invocadas.',
    priority: 'Media',
  },
  {
    day: 39,
    month: 2,
    week: 6,
    title: 'Día 39: Segundo Rito Inquietante (Grandes Shoths Secundarios)',
    building: 'Segundo Rito Inquietante',
    buildingTierLevel: 'Producción Militar Adicional',
    cost: { gold: 3000, wood: 5, ore: 5, mercury: 3 },
    heroActions: [
      'Construye una morada de Grandes Shoths en la base secundaria para sumar crecimiento adicional.',
      'El comandante asalta las reservas de artefactos del rival.',
    ],
    combatTactic: 'Multiplica la presencia de voladores de control en ambos frentes.',
    criticalTip: 'Crecimiento paralelo de criaturas mágicas para control de mapa.',
    priority: 'Alta',
  },
  {
    day: 40,
    month: 2,
    week: 6,
    title: 'Día 40: Segunda Casa de las Cadenas (Concubis Secundarias)',
    building: 'Segunda Casa de las Cadenas',
    buildingTierLevel: 'Producción Militar Tier 5 Adicional',
    cost: { gold: 4000, mercury: 5 },
    heroActions: [
      'Añade una segunda morada de Concubis.',
      'El ejército principal cerca el segundo castillo rival.',
    ],
    combatTactic: 'Genera escuadras de seducción y control mental en la retaguardia enemiga.',
    criticalTip: 'Doble producción de unidades de manipulación táctica.',
    priority: 'Alta',
  },
  {
    day: 41,
    month: 2,
    week: 6,
    title: 'Día 41: Ciudadela del Cisma de la Segunda Base (+50% Crecimiento)',
    building: 'Ciudadela del Cisma (Citadel)',
    buildingTierLevel: 'Crecimiento Militar Secundario',
    cost: { gold: 2500, ore: 10 },
    heroActions: [
      'Aumenta el crecimiento de la base secundaria en +50%.',
      'Prepara los recursos para duplicar la producción de Tier 7.',
    ],
    combatTactic: 'Refuerzos masivos listos para la batalla decisiva de la Semana 7.',
    criticalTip: 'Capacidad de reclutamiento desbordante.',
    priority: 'Alta',
  },
  {
    day: 42,
    month: 2,
    week: 6,
    title: 'Día 42: Segundo Santuario del Abismo (Segunda Morada Tier 7 de Cisma)',
    building: 'Segundo Santuario del Abismo',
    buildingTierLevel: 'Producción Militar Tier 7 Adicional',
    cost: { gold: 10000, ore: 15, mercury: 10 },
    heroActions: [
      'Construye el segundo Santuario para duplicar el reclutamiento de Titanes del Vacío.',
      'Recluta un contingente adicional de Titanes para formar un segundo ejército de invasión.',
    ],
    combatTactic: 'Dos ejércitos con Titanes del Vacío operando en pinza sobre el adversario.',
    criticalTip: 'Tener dos moradas de Tier 7 activas garantiza superioridad militar irreversible.',
    priority: 'Crítica',
  },
  {
    day: 43,
    month: 2,
    week: 7,
    title: 'Día 43: Cofradía de Magos del Cisma Nivel 5 (Ruptura Dimensional y Colapso Cósmico)',
    building: 'Cofradía de Magos Nivel 5',
    buildingTierLevel: 'Magia Divina / Vacío Suprema',
    cost: { gold: 5000, wood: 5, ore: 5, mercury: 10 },
    heroActions: [
      'Aprende hechizos supremos de nivel 5: Colapso Cósmico, Invocación Abisal Mayor y Cero Absoluto de Vori.',
      'El héroe principal domina todo el grimorio mágico de la falla.',
    ],
    combatTactic: 'Desintegra ejércitos enteros con Colapso Cósmico antes del contacto cuerpo a cuerpo.',
    criticalTip: 'El control mágico supremo elimina la ventaja defensiva de cualquier fortaleza rival.',
    priority: 'Crítica',
  },
  {
    day: 44,
    month: 2,
    week: 7,
    title: 'Día 44: Trono del Ojo Cósmico (+2 Moral y +2 Suerte a Criaturas del Cisma)',
    building: 'Trono del Ojo Cósmico (Monumento Supremo)',
    buildingTierLevel: 'Monumento de Facción',
    cost: { gold: 6000, mercury: 6 },
    heroActions: [
      'Erige el Trono del Ojo Cósmico para otorgar +2 de Moral y +2 de Suerte permanentes a todas las tropas.',
      'El ejército principal inicia la ofensiva final.',
    ],
    combatTactic: 'Tasa altísima de golpes afortunados críticos y turnos adicionales por moral radiante.',
    criticalTip: 'Multiplica la efectividad de cada pila de criaturas en combate.',
    priority: 'Alta',
  },
  {
    day: 45,
    month: 2,
    week: 7,
    title: 'Día 45: Segundo Silo de Recursos Regional (+1 Mercurio Diario Adicional)',
    building: 'Segundo Silo de Recursos',
    buildingTierLevel: 'Economía Regional',
    cost: { gold: 0, gems: 3, crystal: 3 },
    heroActions: [
      'Añade un segundo silo para acumular +2 Mercurio diario en el reino.',
      'El héroe secundario asegura las rutas de marcha militar.',
    ],
    combatTactic: 'Sustenta el gasto continuo de maná y reposición de colosos.',
    criticalTip: 'Recursos infinitos para las dos semanas de clímax.',
    priority: 'Media',
  },
  {
    day: 46,
    month: 2,
    week: 7,
    title: 'Día 46: Mejora de Segundo Santuario del Abismo (Titanes del Vacío Adicionales)',
    building: 'Segundo Santuario del Abismo Mejorado',
    buildingTierLevel: 'Tier 7 Mejorado Secundario • Coste: 8.000 Oro, 10 Mineral, 8 Mercurio, 100 Polvo Alquímico',
    cost: { gold: 8000, ore: 10, mercury: 8, alchemicalDust: 100 },
    heroActions: [
      'Mejora el segundo Santuario para reclutar Titanes del Vacío en ambos frentes.',
      'Equipa a los dos comandantes con el contingente de élite.',
    ],
    combatTactic: 'Despliega Titanes del Vacío en ambas alas de batalla con doble turno e inmunidad mágica.',
    criticalTip: 'Dominio absoluto de la masa de criaturas en el campo de batalla.',
    priority: 'Crítica',
  },
  {
    day: 47,
    month: 2,
    week: 7,
    title: 'Día 47: Ojo Omnisciente de Vori (Visión Global Revelada en Todo Jadame)',
    building: 'Ojo Omnisciente de Vori',
    buildingTierLevel: 'Información y Exploración Total',
    cost: { gold: 5000, wood: 10, mercury: 5 },
    heroActions: [
      'Canaliza la mirada colectiva para disipar la niebla de guerra en todo el continente de Jadame.',
      'Localiza la posición exacta de cada héroe y ejército enemigo.',
    ],
    combatTactic: 'Intercepta y embosca a los héroes rivales en terreno favorable sin margen de escape.',
    criticalTip: 'Visión completa del mapa de aventura para asestar el golpe de gracia.',
    priority: 'Alta',
  },
  {
    day: 48,
    month: 2,
    week: 7,
    title: 'Día 48: Resonador de la Falla (+15% Daño Mágico Arcano y de Escarcha)',
    building: 'Resonador de la Falla',
    buildingTierLevel: 'Potenciador Arcano de Facción',
    cost: { gold: 4000, mercury: 6 },
    heroActions: [
      'Construye el Resonador para amplificar el poder de conjuro de todos los hechiceros del Cisma en un +15%.',
      'El comandante principal prepara su reserva de maná para el asedio supremo.',
    ],
    combatTactic: 'Maximiza el daño de proyectiles mágicos y ventiscas sobre las tropas más blindadas del rival.',
    criticalTip: 'Asegura que los hechizos eliminen pilas completas con un solo lanzamiento.',
    priority: 'Alta',
  },
  {
    day: 49,
    month: 2,
    week: 7,
    title: 'Día 49: Gran Cripta de Invocación (Optimización de Suministros)',
    building: 'Gran Cripta de Invocación',
    buildingTierLevel: 'Optimización Logística',
    cost: { gold: 3500, ore: 10 },
    heroActions: [
      'Almacena reservas para abastecer el reclutamiento total del último lunes de la campaña.',
      'Los exploradores se posicionan para guiar la marcha de la horda.',
    ],
    combatTactic: 'Concentra la totalidad del inventario de oro en la compra de la armada definitiva.',
    criticalTip: 'Prepara el último gran día de compras del Día 50.',
    priority: 'Media',
  },
  {
    day: 50,
    month: 2,
    week: 8,
    title: 'Día 50: Forja Abisal de Asedio (Catapultas de Vacío y Arietes de Hielo Negro)',
    building: 'Forja Abisal (Maquinaria de Asedio)',
    buildingTierLevel: 'Maquinaria de Guerra',
    cost: { gold: 3000, wood: 5, ore: 5 },
    heroActions: [
      'Fabrica catapultas de vacío y arietes de hielo negro para el asedio final.',
      'El ejército principal se agrupa ante las puertas de la capital del último oponente.',
    ],
    combatTactic: 'La catapulta de vacío pulveriza murallas y fosos en Turno 1 permitiendo la entrada directa de Titanes.',
    criticalTip: 'Derriba las defensas del castillo enemigo sin sufrir daño de torres defensivas.',
    priority: 'Alta',
  },
  {
    day: 51,
    month: 2,
    week: 8,
    title: 'Día 51: Matriz de Conjuración Eterna (+50% Capacidad de Reserva de Invocación)',
    building: 'Matriz de Conjuración Eterna',
    buildingTierLevel: 'Capacidad Máxima Militar',
    cost: { gold: 5000, ore: 10, mercury: 5 },
    heroActions: [
      'Expande la reserva de tropas para acumular un excedente masivo de Ra\'Shoths y Shoths.',
      'Se completa el ensamblaje de la horda de invasión.',
    ],
    combatTactic: 'Supera en número al rival en una proporción de 5 a 1 en el campo de batalla.',
    criticalTip: 'Masa crítica definitiva que anula cualquier estrategia de microtáctica enemiga.',
    priority: 'Alta',
  },
  {
    day: 52,
    month: 2,
    week: 8,
    title: 'Día 52: Reclutamiento Masivo de Titanes del Vacío y Árbitros de la Falla',
    building: 'Reclutamiento Supremo del Vacío',
    buildingTierLevel: 'Reclutamiento Militar Final',
    cost: { gold: 12000, mercury: 10 },
    heroActions: [
      'Compra la totalidad de los Titanes del Vacío, Árbitros y Concubis disponibles en ambas ciudades.',
      'El ejército alcanza su poder máximo histórico en Jadame.',
    ],
    combatTactic: 'Formación hexagonal completa con vanguardia de Titanes, flancos de Jinetes y centro de Árbitros.',
    criticalTip: 'La mayor fuerza militar de invocación jamás reunida por la facción del Cisma.',
    priority: 'Crítica',
  },
  {
    day: 53,
    month: 2,
    week: 8,
    title: 'Día 53: Sellado de Pasos Estratégicos con Fallas Glaciales Avanzadas',
    building: 'Fallas Glaciales de Paso',
    buildingTierLevel: 'Control Defensivo del Territorio',
    cost: { gold: 4000, ore: 8 },
    heroActions: [
      'Sella todos los portales y pasos de montaña para evitar que el rival intente maniobras de escape.',
      'El adversario queda atrapado en su última fortaleza.',
    ],
    combatTactic: 'Aísla al general enemigo sin posibilidad de recibir refuerzos.',
    criticalTip: 'Cierre total de las vías de suministros del adversario.',
    priority: 'Media',
  },
  {
    day: 54,
    month: 2,
    week: 8,
    title: 'Día 54: Bendición de la Entidad del Vacío (+3 Iniciativa a Toda la Horda del Cisma)',
    building: 'Altar de la Entidad del Vacío',
    buildingTierLevel: 'Bendición de Batalla',
    cost: { gold: 6000, mercury: 8 },
    heroActions: [
      'Canaliza la bendición del vacío para otorgar +3 de Iniciativa y +20% de Velocidad a todo el ejército.',
      'Las tropas actúan en primer lugar en todas las fases del combate.',
    ],
    combatTactic: 'Ataca con todo el ejército antes de que el adversario pueda lanzar su primer hechizo o ataque.',
    criticalTip: 'Garantiza la aniquilación de la primera línea enemiga antes de que puedan reaccionar.',
    priority: 'Crítica',
  },
  {
    day: 55,
    month: 2,
    week: 8,
    title: 'Día 55: Marcha del Fin de los Tiempos de las Huestes del Vacío hacia la Última Fortaleza',
    building: 'Marcha de Guerra del Cisma',
    buildingTierLevel: 'Fase Ofensiva Final',
    cost: { gold: 5000 },
    heroActions: [
      'Inicia el asedio directo a la capital enemiga con las catapultas de vacío y el ejército completo.',
      'Destruye las torres de guardia exteriores.',
    ],
    combatTactic: 'Desintegra las murallas con energía abisal mientras los Grandes Shoths eliminan a los tiradores.',
    criticalTip: 'Último asalto para la conquista completa de Jadame.',
    priority: 'Crítica',
  },
  {
    day: 56,
    month: 2,
    week: 8,
    title: 'Día 56: Dominio Absoluto del Vacío sobre Jadame: Victoria del Cisma',
    building: 'Falla Eterna del Cisma',
    buildingTierLevel: 'Consumación de la Campaña',
    cost: { gold: 15000, ore: 20, mercury: 15 },
    heroActions: [
      'Invocación final y absorción de todas las fortalezas y facciones rivales del continente de Jadame.',
      'Victoria total y definitiva del Cisma tras 56 días de ejecución estratégica perfecta.',
    ],
    combatTactic: 'Hordas interminables de Titanes del Vacío inmortales, Árbitros Mayores y Concubis consumen la resistencia.',
    criticalTip: '¡Estrategia de 56 días de Cisma completada con éxito impecable y rigor canónico absoluto!',
    priority: 'Crítica',
  },
];

console.log('Cisma steps 15-56 prepared:', cismaDays15To56.length);

module.exports = { cismaDays15To56 };
